local _, namespace = ...

-- Fact List
namespace.factslist = {
	"A Night Elf NPC named Crystalfist was added in Moonglade to honor a player known for their dedication to the Druid class.",
	"A Tauren NPC in Thunder Bluff plays a flute version of 'My Heart Will Go On' by Celine Dion.",
	"A bug in Vanilla WoW once allowed hunters to tame boss-level mobs.",
	"A fish in Pandaria has the name 'Wish-Fish' and drops a wish-granting item... sometimes.",
	"A ghostly gnome NPC in Icecrown pays tribute to a player who dedicated thousands of hours to helping others level.",
	"A gnome NPC in Gnomeregan mentions plans for world domination, but no one takes him seriously.",
	"A gnome NPC in the Brawler’s Guild shouts 'I must break you!'—a reference to Rocky IV.",
	"A goblin NPC named 'Boom Boom' in Booty Bay mentions inventing the Azerothian equivalent of dynamite.",
	"A gravestone in the Hillsbrad Foothills was added for a player who loved the zone and passed away. The inscription reads, 'Rest in peace, friend.'",
	"A hidden NPC in Stranglethorn Vale sells bananas to players. Why? No one knows.",
	"A hidden NPC in the Grizzly Hills serenades players with a fishing song.",
	"A hidden Pandaren NPC brews tea in the Jade Forest and offers it to passing players.",
	"A hidden cave in Winterspring contains an altar surrounded by snow-covered animal bones. Its purpose remains unknown.",
	"A hidden vendor in Winterspring sells a pattern for a Frostsaber mount.",
	"A quest in the Barrens involves investigating why kodos mysteriously vanish into the desert.",
	"A rare NPC named Stomper Kreeg in Dire Maul sells alcohol that gives a temporary stat boost but also lowers your vision.",
	"A rare mob in Sholazar Basin named 'King Krush' has terrified many hunters with its sudden roar.",
	"A rare spawn named Terry the Tornado was added in honor of a player who was known for their whirlwind-like energy and enthusiasm in the game.",
	"A rare toy called the 'Flame Eater' lets you breathe fire on other players.",
	"A ruined village in Desolace hints at an Old God’s influence, with eerie whispers heard at night.",
	"A secret questline in Azshara lets players unlock a murloc battle companion.",
	"A ship in Stormsong Valley features a tribute to a guild that lost a beloved member who was a naval officer in real life.",
	"A small goblin NPC in Ratchet claims to be inventing a 'teleporting sandwich.' It's unclear if he succeeded.",
	"A spirit bear named Frostpaw in Grizzly Hills was added to honor a player who loved the zone and was an avid supporter of conservation in real life.",
	"An NPC in Booty Bay references the Pirates of the Caribbean movie franchise.",
	"An NPC in Dalaran tells players he’s been polymorphed into a sheep for years.",
	"An NPC in Nagrand references the famous line ‘This is not my beautiful house!’ from the Talking Heads song.",
	"An NPC in Westfall named Miguel’s Ghost was added to commemorate a dedicated WoW player who passed away and loved adventuring in Azeroth.",
	"An NPC in the Scarlet Monastery crypts was added to honor a player who loved the dungeon and spent countless hours exploring its lore.",
	"An NPC named Anaya Dawnrunner was added in Ashenvale to commemorate a Night Elf enthusiast who contributed to the WoW community.",
	"An NPC named Ezra 'Phoenix' Wheathoof was added in Thunder Bluff to honor a young fan who passed away. He was also given the voice for Ahab Wheathoof, a character with a special questline.",
	"Arakkoa from Outland were originally guardians of the Apexis Crystals.",
	"Arthas' sword Frostmourne was crafted by the Nathrezim, masters of manipulation and deceit.",
	"Arthas’ horse, Invincible, is one of the most sought-after mounts in the game.",
	"Bag space was extremely limited in Vanilla WoW, and managing inventory was a constant struggle.",
	"Battlegrounds were not available at launch and were added later with patches.",
	"Before mounts, players used to joke that Druids had the first 'vehicle'—Travel Form.",
	"Before transmogrification, many players wore mismatched gear that led to comical fashion disasters.",
	"Black Temple's elevator is infamous for catching unsuspecting players who don't notice it descending or ascending, leading to sudden deaths.",
	"Blizzard added a wandering monk NPC named Wei in Pandaria as a tribute to a player who passed away and had a deep love for the Pandaren lore.",
	"Blizzard added an NPC named Caylee Dak to honor a player who passed away. The character holds a note that was written by the player's real-life wife.",
	"Blizzard created a spirit healer NPC in Azshara to honor a player who always helped others in-game.",
	"Blizzard developers used to host trivia contests during in-game events.",
	"Blizzard once added a 'Dance Studio' in patch notes as an April Fool’s joke.",
	"Blizzard once added a goblin NPC named 'Kazkaz the Infallible' who constantly fails his experiments.",
	"Blizzard once added a toy that spawns a tiny disco floor for everyone to dance on.",
	"Blizzard once hid an NPC named Jon in Shadowmoon Valley as a tribute to a long-time player.",
	"Blizzard once hosted an in-game memorial for a player who passed away.",
	"Blizzard once released a patch that accidentally made hunters' pets invincible in PvP.",
	"Blizzard once turned a player’s cat into an in-game NPC as a memorial.",
	"Brewfest mugs in WoW have unique toasts when clicked, including one that references real-world Oktoberfest traditions.",
	"Cat Form for Druids originally didn’t allow them to auto-attack, requiring manual input for every strike.",
	"Classic WoW players often roleplayed as chefs to sell buff food in major cities.",
	"Darkmoon Faire NPCs have some of the creepiest dialogue in the game. Read it closely.",
	"Darkmoon Faire’s founder, Silas Darkmoon, is shrouded in mystery, with ties to Old God lore.",
	"Death Knights start at level 55 because lore-wise, they 'skipped' normal life. Convenient!",
	"Did you know that Thrall’s name means 'slave' in Old Norse?",
	"Dire Maul was one of the first 'endgame' dungeons introduced after the game’s initial launch.",
	"Draenei crystals are infused with holy energy, which makes them glow.",
	"Draenei spaceships are powered by magic crystals called Naaru cores.",
	"Dragon Soul’s elevator leading to Ultraxion occasionally claimed lives, especially for players lagging behind the group.",
	"During Brewfest, players can complete a quest that involves riding a ram and stealing kegs.",
	"During Brewfest, players can complete the 'Save Brewfest!' questline to defeat Coren Direbrew and earn seasonal rewards.",
	"During Brewfest, players can earn a ‘Brewmaster’ title by completing seasonal achievements.",
	"During Brewfest, players can fight a boss named Coren Direbrew to earn unique mounts.",
	"During Brewfest, players can ride rams to collect kegs and earn special seasonal achievements.",
	"During Children’s Week, you can take orphans on adventures across Azeroth.",
	"During Hallow’s End, players can fight the Headless Horseman for a chance to earn his fiery mount.",
	"During Hallow’s End, you can trick-or-treat for rare items and spooky rewards.",
	"During Legion, Demon Hunters could double-jump, making them the most agile class in the game.",
	"During Legion, players could obtain a fishing artifact called the ‘Underlight Angler.’",
	"During Winter Veil, you can find sneaky goblins disguised as Santa Claus in various cities.",
	"During Wrath of the Lich King, players could duel on the edge of Dalaran and knock each other off.",
	"During Wrath pre-patch events, zombie infections could spread across entire cities.",
	"During early WoW expansions, fishing contests rewarded unique mounts, pets, and gear.",
	"During the AQ War Effort, certain NPCs in capital cities had unique dialogue lines about the massive resource collection effort.",
	"During the Cataclysm beta, Deathwing would randomly appear and kill players with a massive flame attack. This feature was removed before launch.",
	"During the Cataclysm, Deathwing scarred Azeroth permanently with massive earthquakes.",
	"During the Cataclysm, most players forgot about Gilneas after leveling through it.",
	"During the Cataclysm, the Thousand Needles zone was flooded, transforming it into a saltwater lake.",
	"During the MoP expansion, the Tillers farm was a hidden favorite for casual players.",
	"During the WoW beta, Mages could teleport other players... anywhere. Chaos ensued.",
	"During the Wrath of the Lich King expansion, players completed the 'Wrathgate' questline, leading to one of the most iconic cinematics in WoW history.",
	"During the pre-Wrath zombie plague event, players infected with a zombie virus could spread it, turning entire cities into chaos.",
	"During the pre-expansion events for Legion, the Burning Legion invaded random zones, causing chaos.",
	"During the zombie plague pre-event for Wrath of the Lich King, entire cities were overrun by infections.",
	"Each expansion of WoW introduced at least one major lore character as a raid boss.",
	"Elune, the goddess of the Night Elves, is speculated to have a connection to the Naaru, though the truth is shrouded in mystery.",
	"Epic mounts in Vanilla WoW cost 1,000 gold, a fortune for most players at the time.",
	"Every major city in WoW has an innkeeper who sells a unique, regional delicacy.",
	"Every playable class in WoW has at least one spell inspired by Dungeons & Dragons mechanics.",
	"Forsaken Apothecaries create plague experiments using unwilling test subjects, some of whom are still alive.",
	"Frost Mages used to kite raid bosses indefinitely during glitches. Blizzard patched it out.",
	"Frost Mages were nicknamed 'ice cannons' for their powerful crowd control abilities in PvP.",
	"Frostfire Ridge in Draenor contains hidden hot springs guarded by elemental creatures.",
	"Garrosh Hellscream's voice actor also played multiple NPCs, including a surprisingly cheerful goblin.",
	"Gnomes used to have a racial ability called 'Escape Artist' that was great in PvP.",
	"Gnomes were added as a playable race partly as comic relief for the Alliance.",
	"Goblin engineering is so volatile that early WoW players blew themselves up crafting items!",
	"Goblin rockets were initially designed to explode harmlessly, but they gained destructive power after a coding mishap.",
	"Goblins are known for their explosive mining techniques, which sometimes backfire spectacularly.",
	"Goblins are the only race in WoW to have their own functional rocket transport network.",
	"Goblins have a secret motto: 'Time is money, friend!' It’s not so secret anymore.",
	"Goblins invented rockets, but they never patented them. That’s why everyone uses them.",
	"Goblins used to explode their own mounts for fun before it was patched out.",
	"Goblins were added as a playable race because of their popularity as quirky NPCs.",
	"Goldshire is infamous on certain servers for being the epicenter of unusual roleplay activities.",
	"Goldshire's famous (or infamous) inn has more recorded roleplay sessions than any other WoW location.",
	"Gryphons were first introduced as Alliance mounts in Warcraft II.",
	"Heart of Fear's elevator transitions became a common death trap for players unfamiliar with the raid's pacing.",
	"Helya’s Kvaldir pirates are bound to her will and doomed to wander the seas for eternity, never finding rest.",
	"Hidden in Pandaria is a wandering monk who references famous kung fu movies.",
	"Hogger is so infamous that he has his own raid encounter in the Hearthstone game.",
	"Hogger, a low-level gnoll in Elwynn Forest, became a meme as one of the deadliest starter mobs.",
	"Hunters used to have to feed their pets regularly to keep them happy, or they’d run away.",
	"Hunters used to need ammunition to shoot their ranged weapons, taking up bag space.",
	"If you /wave at certain NPCs, they will wave back. Try it on a guard!",
	"If you duel in the Gurubashi Arena, everyone can loot your corpse if you die.",
	"If you jump enough times as a Gnome, other players might ask you to stop. It’s too cute.",
	"If you jump multiple times on a Gnomish X-Ray Specs toy, your character sometimes glitches into a skeleton pose.",
	"If you repeatedly /chicken at random chickens in the game, one might eventually cluck back and offer a secret quest.",
	"If you spam the /moo emote as a Tauren, sometimes you get a special response.",
	"If you swim far enough out to sea, fatigue will kill you faster than any shark can.",
	"Illidan Stormrage's blindfold is enchanted to help him sense demonic energies.",
	"In Ashenvale, players can find abandoned troll camps filled with cryptic carvings.",
	"In Ashenvale, players can find ancient ruins of the Night Elves' first cities.",
	"In Azeroth, all female Draenei canonically wear high heels. Always ready for a party.",
	"In Azshara, there’s a hidden underwater cavern filled with glowing jellyfish and ancient murals.",
	"In Blackrock Depths, the long elevator ride to Emperor Thaurissan gave impatient players plenty of time to fall to their deaths.",
	"In Classic WoW, it could take weeks to gather enough materials for a single raid attempt.",
	"In Classic WoW, players had to manually discover flight paths by visiting them in person.",
	"In Classic WoW, rogues could vanish mid-battle, confusing raid bosses completely.",
	"In Dalaran, there’s a talking rat NPC named Sneaky Pete who references classic spy movies.",
	"In Dalaran, there’s a vendor who sells cheese that’s 'aged for a millennium.' Expensive, though.",
	"In Deadwind Pass, players report hearing unsettling noises while exploring the area around Karazhan.",
	"In Draenor, you can fish up a shark mount called the ‘Riding Shark.’",
	"In Drustvar, players uncover evidence of witchcraft, dark rituals, and human sacrifices performed by the Heartsbane Coven.",
	"In Icecrown Citadel, you encounter tortured souls begging for release, including those trapped in weapons like the Shadowmourne axe.",
	"In Icecrown, a memorial was added for a player who passed away during the Wrath of the Lich King expansion's release, with a small shrine featuring a candle.",
	"In Icecrown, you can find a wrecked Argent Crusade caravan with journals hinting at failed expeditions.",
	"In Karazhan, there's an upside-down room where gravity clearly doesn't exist.",
	"In Legion, NPCs sometimes broke the fourth wall and commented on how many heroes exist.",
	"In Legion, a Hunter NPC named Ara'lon was inspired by a player who had a deep love for the class and passed away unexpectedly.",
	"In Legion, players could loot hidden artifact appearances by solving puzzles.",
	"In Legion, players could solo older raids and collect every artifact appearance.",
	"In Legion, the quest 'Puzzle Box of Yogg-Saron' has players decipher cryptic and unsettling whispers from the Old Gods.",
	"In Maldraxxus, failed creations and broken souls are discarded into heaps, left to rot or be consumed by stronger beings.",
	"In Maldraxxus, souls deemed unworthy are broken down into anima, essentially consuming their essence for power.",
	"In Maldraxxus, the House of Eyes trained the most skilled spies in the Shadowlands.",
	"In Mechagon, you can build your own customizable mechanical mounts.",
	"In Mists of Pandaria, the Brewery dungeon has a barrel you can click that starts a drinking contest.",
	"In Moonglade, players can find ancient trees with carved faces, symbolizing druidic wisdom.",
	"In Moonglade, you can find a giant turtle that’s over 10,000 years old.",
	"In Moonglade, you can find ancient trees with faces carved into their bark.",
	"In Nagrand, there’s a floating platform with a single chair and telescope, seemingly abandoned.",
	"In Northrend, you can find a small snowman village hidden near the Storm Peaks.",
	"In Northrend, you can find skeletal remains of ancient sea monsters washed ashore.",
	"In Orgrimmar, the Auction House has secret goblin tunnels connecting different areas.",
	"In Orgrimmar, there’s an unused door in the Cleft of Shadows that was rumored to lead to a secret warlock lair.",
	"In Outland, some NPCs still reference the Burning Crusade as if it’s happening right now.",
	"In Outland, you can find an NPC named 'Haris Pilton' selling overpriced bags. Yes, that's a joke.",
	"In Outland’s Netherstorm, there’s a field of inactive mana golems that are part of no quests or events.",
	"In Pandaria, the Hozen view time differently, calling the past ‘yesterday’ and the future ‘long yesterday.’",
	"In Pandaria, the quest 'Finish This!' has players complete a half-drawn painting by defeating enemies to 'paint' the canvas.",
	"In Pandaria, the waterfall in Jade Forest hides a tiny shrine dedicated to an unnamed Pandaren philosopher.",
	"In Pandaria, there’s a shrine dedicated to a cat named Socks that was a tribute to a Blizzard developer's pet.",
	"In Pandaria, you can find a hidden shrine dedicated to a cat named Socks.",
	"In Revendreth, the souls of sinners are dragged into cages and drained of anima, their screams filling the air.",
	"In Scholomance, students of necromancy dissect corpses in the name of dark magic and reanimation.",
	"In Shadowlands, Revendreth is a realm for sinful souls to atone, but many are tortured endlessly for their misdeeds rather than redeemed.",
	"In Shadowlands, Revendreth is a realm where sinful souls atone for their misdeeds through torment.",
	"In Shadowlands, the quest 'Maw Walkers' plays on the lore of your character becoming one of the few capable of navigating the Maw.",
	"In Shadowmoon Valley, ghostly orcs can still be seen performing their ancient rituals.",
	"In Shadowmoon Valley, there’s a floating orb high above the ground that emits whispers but has no known purpose.",
	"In Siege of Orgrimmar, the elevator after Malkorok would often catch players off guard, leading to unexpected deaths.",
	"In Silithus, there’s a small cave with carvings that resemble Old God tentacles, suggesting a deeper corruption in the zone.",
	"In Silverpine Forest, Forsaken forces desecrate graves and raise fallen humans into undeath, regardless of their wishes in life.",
	"In Silverpine Forest, Forsaken grave robbers desecrate human burial sites, raising the dead as unwilling soldiers.",
	"In Stormwind’s library, there are books that describe the histories of zones like Stranglethorn Vale and the Plaguelands.",
	"In Sunwell Plateau, the elevator leading to Felmyst was another infamous trap for players rushing to their next encounter.",
	"In Tirisfal Glades, the dead sometimes rise on their own, wandering aimlessly as restless spirits.",
	"In Vanilla WoW, Gnomeregan had a locked room called the 'Hall of Gears' that was never opened officially.",
	"In Vanilla WoW, druids had to farm rare plants for reagents to cast some of their spells.",
	"In Vanilla WoW, hunters had to feed their pets to maintain loyalty, or they risked running away.",
	"In Vanilla WoW, players had to manually discover flight paths by visiting each flight master.",
	"In Vanilla WoW, raids like Onyxia’s Lair required lengthy attunement questlines to access.",
	"In Vanilla WoW, rogues needed to brew their own poisons using a specific skill.",
	"In Vanilla WoW, the only way to talk to the opposing faction was through emotes, like /wave.",
	"In Vanilla WoW, warlocks had to farm Soul Shards from enemies to summon players or cast some of their spells.",
	"In Vanilla WoW, you had to craft resistance gear to survive certain raid encounters.",
	"In Vanilla, people spent hours farming for rare mounts like the Baron Rivendare's Deathcharger.",
	"In Winterspring, there’s an NPC named Jangdor Swiftstrider who references old Warcraft III lore about furbolg shamans.",
	"In Winterspring, you can still find NPCs referencing the epic Wintersaber grind.",
	"In WoW Classic, players had to carry quivers for arrows or they couldn’t attack as Hunters.",
	"In WoW, chickens are smarter than they look. There's a secret questline if you /chicken at one!",
	"In Wrath of the Lich King, players could accidentally kite raid bosses into Dalaran, causing chaos.",
	"In Wrath of the Lich King, players could duel on the edges of Dalaran and knock each other off.",
	"In Zandalar, the Blood Trolls worship G’huun, an artificial Old God created by the Titans.",
	"In Zandalar, the Blood Trolls worship the Blood God G’huun, an artificial Old God.",
	"In Zangarmarsh, players can stumble upon a mushroom field that glows under the moonlight.",
	"In early WoW, Druids were considered 'jack of all trades, master of none' due to their versatile skill set.",
	"In early WoW, jumping off Thunder Bluff accidentally was a rite of passage for Taurens.",
	"In early WoW, mounts required players to grind gold and reputations for training and riding skill.",
	"In early WoW, players used to sit around campfires for no reason other than vibes.",
	"In the Barrens, there's a neutral Kodo skeleton NPC named 'Old Blanchy’s Cousin.'",
	"In the Barrens, you can find a mysterious oasis guarded by aggressive creatures.",
	"In the Battle for Azeroth expansion, you can find NPCs making fun of previous expansions’ plot holes.",
	"In the Burning Crusade, flying mounts were introduced, changing the way players explored Azeroth.",
	"In the Burning Crusade, the Tempest Keep dungeons originally shared some design elements with the Eye of Eternity raid.",
	"In the Drustvar zone, players can find stone runes that glow faintly during rainstorms.",
	"In the Emerald Dreamway, druids can find dream versions of zones that were never officially added to the game.",
	"In the Howling Fjord, vrykul warriors believe dying in battle earns them a place in Valhalla.",
	"In the Karazhan Opera Event, some NPCs reference Shakespearean plays, but in Azerothian style.",
	"In the Scarlet Monastery, fanatical crusaders burn people alive, believing it purifies their souls from undeath.",
	"In the Shadowlands, souls who fail their trials are thrown into the Maw, where they suffer eternal torment and oblivion.",
	"In the Swamp of Sorrows, a hidden cave contains remnants of a lost Orcish scouting party.",
	"In the Wailing Caverns, there’s a hidden cave with glowing mushrooms that doesn’t serve any quest purpose.",
	"In the Whispering Forest of Tirisfal Glades, faerie dragons perform a haunting ritual surrounded by eerie whispers and glowing light.",
	"In the Wrath pre-patch, the zombie plague turned every player into a griefing machine.",
	"In the original WoW beta, Dwarves could play as Mages, but it was removed before launch.",
	"In the original WoW beta, players could kill quest-giving NPCs, breaking quests for everyone.",
	"Kel'Thuzad, the lich and servant of the Lich King, was a former mage of Dalaran who willingly embraced necromancy and helped spread the plague of undeath.",
	"Khadgar’s beard is so iconic that players often joke about him hiding magic items in it.",
	"Kkthnx made this addon so he could procrastinate updating his alts’ gear.",
	"Kkthnx, creator of KkthnxUI and WTFacts, is probably coding this addon while standing in the Auction House.",
	"Kkthnx, the brains behind this addon, has written more lines of code than he’s run dungeons. Priorities.",
	"Kkthnx, the genius behind KkthnxUI, made this addon because Azeroth can always use more random facts.",
	"Leveling in the Barrens was considered a rite of passage due to its vast and confusing terrain.",
	"Mages in early WoW used to make a killing selling food and water to players.",
	"Mages were the first class to have teleportation spells for instant travel.",
	"Many NPCs in WoW were named after Blizzard employees' pets.",
	"Many quests in Vanilla WoW lacked clear instructions, requiring players to explore and experiment.",
	"Mechagnomes have a hidden workshop where they experiment with transforming organic life into machinery.",
	"Mechagnomes were introduced in Battle for Azeroth as a playable race for the Alliance.",
	"Meeting stones in Vanilla WoW were originally intended for finding groups, not summoning players.",
	"Mount Hyjal was inaccessible in Vanilla but had a hidden entrance that players exploited.",
	"Mounts in Vanilla WoW required players to buy both the riding skill and the mount separately.",
	"Murlocs are based on a combination of real-world fish and amphibian species, exaggerated for comedic effect.",
	"Murlocs communicate using their own language, but no full translation has ever been confirmed.",
	"Murlocs have a higher chance to drop green items than most other mobs in the game.",
	"Murlocs have their own language, but no one has successfully translated it—yet.",
	"Murlocs were added to Warcraft lore late in development because devs wanted 'something weirder.'",
	"Naga were once Night Elves, transformed after the Well of Eternity exploded.",
	"On the Timeless Isle, you can find NPCs referencing the slow passage of time with existential musings.",
	"Paladins and Shamans were faction-exclusive classes, with Paladins on Alliance and Shamans on Horde.",
	"Pandaren NPCs often quote proverbs that combine wisdom with humor, like 'The bamboo bends, but it does not break.'",
	"Players can find a friendly murloc named Murky, Blizzard’s first official murloc mascot.",
	"Players can find a hidden tribute to Robin Williams in Draenor as a genie NPC named 'Robin.'",
	"Players in Classic WoW created 'bridges' by standing on each other to reach secret places.",
	"Players in early WoW loved to kite world bosses into major cities for laughs... and mass deaths.",
	"Players in early WoW would duel in front of Stormwind for hours, betting gold on matches.",
	"Players used to kite world bosses like Kazzak into major cities, causing chaos for unsuspecting players.",
	"Players who complete 'Insane in the Membrane' earn one of the hardest titles in the game.",
	"Players who earn the title 'Bloodsail Admiral' lose reputation with most goblin cities.",
	"Players who earn the title 'The Insane' must max out reputations with factions that despise each other.",
	"Players who earned the title 'The Insane' had to grind reputations with factions that hated each other.",
	"Professions in Vanilla WoW were time-consuming but rewarded players with unique items and gear.",
	"PvP ranks in Vanilla WoW required weekly grinding and competition to maintain your rank.",
	"Queen Azshara’s palace contains secret rooms filled with ancient Highborne treasures.",
	"Raid groups in Vanilla WoW could include up to 40 players, making coordination a massive challenge.",
	"Robin Williams, a huge fan of World of Warcraft, was immortalized as a genie NPC in Draenor named Robin.",
	"Rogues in Vanilla WoW could pickpocket unique items like lockboxes and junk.",
	"Rogues in Vanilla could one-shot people using Ambush if they stacked enough Agility.",
	"Shaman totems once had to be placed individually—and they could be destroyed by enemies.",
	"Shattrath City's elevator in Terokkar Forest is notorious for causing deaths during daily quest runs in Burning Crusade.",
	"Some Forsaken NPCs in Tirisfal Glades still wear the armor they died in.",
	"Some Forsaken NPCs still reference their human lives in odd and unsettling ways.",
	"Some Murlocs in Elwynn Forest wear fishing hats, suggesting they’ve adapted to human habits.",
	"Some Night Elf ruins in Azeroth still hold ancient moonwell water with magical properties.",
	"Some Tauren NPCs reference the phrase 'bull market,' a nod to financial humor.",
	"Some Tauren totems in Thunder Bluff are carved with stories of their ancestors’ bravery.",
	"Some WoW zones like Azshara were originally supposed to be major cities but were scrapped.",
	"Some bosses in raids will taunt players by using their own voice lines against them.",
	"Some early raid bosses used to have unlootable corpses if players killed them incorrectly.",
	"Some fishing spots in Azeroth are so rare they only appear during in-game weather events.",
	"Some high-level gear in Vanilla WoW required rare materials and weeks of farming to craft.",
	"Some mobs in WoW Classic dropped gray items with hilariously long names just for fun.",
	"Some of the NPCs in Booty Bay are named after pirates from real history.",
	"Some of the Zandalari Trolls’ architecture predates the Sundering of Azeroth.",
	"Some of the early in-game books reference real-world myths, such as Norse and Greek mythology.",
	"Some of the goblin trade cartels engage in piracy, rivaling traditional ships on the seas.",
	"Some of the jokes told by Troll NPCs in the game are puns on real-world Rastafarian culture.",
	"Some of the undead NPCs in Tirisfal Glades reference their former lives in cryptic and eerie ways.",
	"Some of the worgen NPCs in Gilneas quote lines from Victorian literature.",
	"Some quests in Shadowlands allow you to explore the memories of dead NPCs.",
	"Some rare creatures in Azeroth drop vanity items, like hats, glasses, and even cosmetic swords.",
	"Some rare mobs drop vanity items like cooking hats or pirate costumes.",
	"Some rare spawns in Northrend drop vanity pets instead of gear or crafting materials.",
	"Stormwind Harbor has a hidden merchant who sells items related to fishing.",
	"Tauren totems are carved with symbols that tell their tribe’s history.",
	"Teldrassil, the World Tree, was corrupted by an Old God shortly after it was grown.",
	"Tempest Keep's elevator is one of the most dangerous in WoW, often surprising players after a long boss fight.",
	"The 'Battle for Undercity' questline in Wrath of the Lich King had players fight alongside faction leaders to reclaim the city, but it was later removed from the game.",
	"The 'Dancing Troll Village' is a hidden zone with NPCs partying 24/7. It's amazing.",
	"The 'Disgusting Oozeling' pet gives players a slight debuff when summoned.",
	"The 'Lazy Peons' in the Orc starting zone are a callback to a Warcraft III mission.",
	"The 'Leeroy Jenkins' achievement requires running into a group of mobs in Upper Blackrock Spire.",
	"The 'Onyxia’s Lair Attunement' questline was infamous for its length and complexity, but completing it was a badge of honor.",
	"The 'Underbelly' in Dalaran is a hot spot for PvP... and for fishing rare items.",
	"The 'elevator boss' in Blackwing Descent has claimed countless lives, with players falling to their deaths due to mistiming the jump.",
	"The Aldor and Scryer factions in Shattrath used to fight openly in the city.",
	"The Alliance and Horde fight over resources in Silithus, even though it’s a barren wasteland.",
	"The Argent Dawn faction was formed to protect Azeroth from undead threats after the Third War.",
	"The Argent Tournament grounds in Northrend were originally going to be a raid zone.",
	"The Argent Tournament was a test of strength for heroes preparing to face the Lich King.",
	"The Argent Tournament was introduced in Wrath of the Lich King as a preparation for Icecrown Citadel.",
	"The Ashbringer sword was a long-standing WoW legend before it was added to the game in Wrath of the Lich King.",
	"The Ashbringer sword was said to be forged from pure Light and could destroy the undead instantly.",
	"The Auction House in Booty Bay is the only one accessible to both Horde and Alliance.",
	"The Auction House was originally limited to capital cities and required travel for cross-faction trading.",
	"The Auction House was originally so buggy that gold duping exploits became rampant.",
	"The Barrens is so large that it was once joked it should have its own chat channel for players.",
	"The Barrens is so vast that players once joked it should have its own chat channel.",
	"The Barrens used to have an NPC named 'Mankrik’s Wife' before she disappeared.",
	"The Black Temple raid was originally Illidan’s fortress and training ground for Demon Hunters.",
	"The Black Temple was once a sanctuary for the Draenei before Illidan took it over.",
	"The Blackrock Depths arena has a hidden room with a treasure chest, but it’s locked behind specific conditions.",
	"The Blackrock Orcs were once allies of the Horde but betrayed them for power.",
	"The Blackrock Orcs were originally allies of the Horde but betrayed them for power.",
	"The Blackrock Spire dungeon is a massive fortress with hidden corridors and Easter eggs.",
	"The Blackrock clan orcs are known for their loyalty to their warlords and mastery of the forge.",
	"The Blingtron 4000 robot distributes gifts, but it’s also been known to start wars between players.",
	"The Blood Elf capital, Silvermoon, still bears scars from Arthas’ attack during the Third War.",
	"The Borean Tundra in Northrend features giant steam vents that keep the zone semi-habitable.",
	"The Brawler’s Guild features increasingly difficult solo challenges for players to conquer.",
	"The Bronze Dragonflight controls the flow of time and protects Azeroth’s history.",
	"The Bronze Dragonflight protects the timeline from interference by the Infinite Dragonflight.",
	"The Burning Legion’s leader, Sargeras, was once a champion of the Titans before his fall.",
	"The Burning Legion’s leader, Sargeras, was once a champion of the Titans before succumbing to corruption.",
	"The Burning Legion’s soldiers come from countless conquered worlds across the cosmos.",
	"The Cataclysm expansion flooded the Thousand Needles zone, creating a massive saltwater lake.",
	"The Caverns of Time contain unused portals that were once planned for cut content, including the War of the Shifting Sands.",
	"The Caverns of Time elevators were initially slow but later updated, though players still occasionally fall due to haste.",
	"The Caverns of Time in Tanaris allow players to witness Azeroth’s most important historical events.",
	"The Caverns of Time include instances where you must protect events from being altered by the Infinite Dragonflight.",
	"The Caverns of Time let players experience some of Azeroth’s most iconic historical events.",
	"The Crystalsong Forest is named after the powerful crystals growing throughout the zone.",
	"The Dancing Troll Village in Hinterlands is a hidden location with non-stop music.",
	"The Dark Portal is one of the oldest structures in Azeroth, built by the Orcs to invade.",
	"The Dark Portal was originally created by the orc warlock Gul’dan to invade Azeroth.",
	"The Darkmoon Faire features a roller coaster you can actually ride.",
	"The Darkmoon Faire has an eerie forest with glowing eyes that follow you.",
	"The Darkmoon Faire's founder, Silas Darkmoon, is a mysterious gnome who rarely appears in public.",
	"The Darkmoon Faire’s forest area contains a ghostly NPC who disappears when approached.",
	"The Darkmoon Faire’s leader, Silas Darkmoon, is rumored to have connections to Old God worship, as evidenced by the Faire’s unsettling atmosphere and cryptic items.",
	"The Darkmoon Rabbit boss is a reference to the killer rabbit from Monty Python and the Holy Grail.",
	"The Darkmoon Rabbit is a hidden world boss inspired by Monty Python.",
	"The Deadmines contains the remains of past adventurers who failed to escape its deadly traps.",
	"The Deadmines dungeon has a hidden parrot named Captain Cookie who can drop loot.",
	"The Deadmines in Vanilla WoW had a secret room with a goblin engineer’s workshop that wasn’t tied to any quests.",
	"The Deadwind Pass zone around Karazhan emits faint sounds of whispers and chains at night.",
	"The Death Knight starting experience involves players being forced to slaughter innocent villagers under the Lich King's command.",
	"The Death Knight starting zone features a mission where players are forced to slaughter innocent villagers.",
	"The Deeprun Tram connects Stormwind and Ironforge but also has a giant underwater tunnel.",
	"The Demon Hunter’s ability to glide comes from their spectral wings.",
	"The Draenei originally fled their homeworld of Argus to escape the Burning Legion.",
	"The Drakkari trolls in Northrend sacrificed their own animal gods to gain power when they were desperate to fight the Scourge.",
	"The Drakkari trolls sacrificed their own gods to protect themselves from the Scourge.",
	"The Emerald Dream is a vision of Azeroth untouched by mortal hands.",
	"The Emerald Dream was originally planned as an expansion but ended up being raid content instead.",
	"The Emerald Nightmare distorts Azeroth’s most serene natural landscapes into horrifying versions, filled with corrupted creatures and twisted flora.",
	"The Emerald Nightmare is a corrupted version of the Emerald Dream, filled with horrors created by the Old God N'Zoth to destroy Azeroth's natural order.",
	"The Emerald Nightmare raid was based on corrupted versions of zones in the Emerald Dream.",
	"The Eternal Palace in Nazjatar is the seat of Queen Azshara’s power.",
	"The Ethereal race is based on sci-fi depictions of energy beings.",
	"The Ethereal race trades in powerful magical artifacts across the cosmos.",
	"The Exodar is a crashed spaceship that the Draenei turned into their capital.",
	"The Eye of Eternity raid boss Malygos occasionally says lines that reference classic sci-fi films, like Star Wars.",
	"The Feast of Winter Veil was inspired by real-world holidays like Christmas and features unique recipes and gifts.",
	"The Fel Reaver in Hellfire Peninsula is infamous for sneaking up on distracted players with its loud stomping.",
	"The Fel Reaver in Hellfire Peninsula is infamous for sneaking up on distracted players.",
	"The Fel Reaver in Outland has a surprising amount of fan art, despite traumatizing players.",
	"The Firelands raid features Ragnaros reborn, this time with legs!",
	"The Firelord Ragnaros controls an army of elementals in the Plane of Fire.",
	"The Forsaken Apothecaries conduct experiments in alchemy to create plagues and poisons.",
	"The Forsaken Apothecaries conduct experiments to refine plagues and poisons for their war effort.",
	"The Forsaken Apothecaries experiment on living humans and animals to refine their deadly plague.",
	"The Forsaken built the Undercity within the ruins of Lordaeron after Arthas' betrayal.",
	"The Forsaken faction was originally neutral but became Horde after Sylvanas joined them.",
	"The Forsaken use blight bombs in battle, a strategy derived from their plague experiments.",
	"The Forsaken were originally part of the Scourge before Sylvanas broke them free.",
	"The Forsaken’s plague experiments often reference real-world toxicology practices.",
	"The Garrison system in Warlords of Draenor lets players build and customize their own base.",
	"The Goblin Zeppelin is powered by Goblin ingenuity—and a lot of duct tape.",
	"The Goblin Zeppelin system was introduced as an affordable way for Horde players to travel between continents.",
	"The Goblin trikes were added in Cataclysm because Blizzard wanted the Horde to have a vehicle-inspired mount to rival the Alliance's motorcycles.",
	"The Goldshire innkeeper has one of the most haunted WoW locations upstairs. Don’t visit at night.",
	"The Green Dragonflight’s hidden glades in Feralas are tied to the Emerald Dream but have no current lore purpose.",
	"The Grizzly Hills zone features an NPC who plays a lute by a campfire, creating a relaxing atmosphere.",
	"The Grizzly Hills zone features music that’s widely considered one of the best soundtracks in WoW.",
	"The Haunted Memento from Naxxramas summons a shadowy ghost to follow players around.",
	"The Hearthstone card game started as a simple WoW mini-game concept.",
	"The Horde airship captains occasionally argue over the intercom. It's worth eavesdropping on.",
	"The Hozen of Pandaria have their own unique language, often filled with monkey-themed slang.",
	"The Iron Horde in Warlords of Draenor used primitive weapons enhanced by technology.",
	"The Ironforge airport is a hidden area that has existed since Vanilla WoW.",
	"The Jinyu race in Pandaria can 'listen' to the water to predict the future.",
	"The Kalu’ak in Northrend are Tuskarr fishermen who also build intricate carvings.",
	"The Karazhan Chess Event has caused more wipes than actual bosses in that raid.",
	"The Karazhan Crypts, an unused area, contain a section called the 'Upside-Down Sinners,' where bodies float eerily underwater, chained by their feet.",
	"The Leeroy Jenkins achievement was added to honor the viral video of a player charging into battle recklessly.",
	"The Leeroy Jenkins meme originated from a player in Upper Blackrock Spire. Never forget.",
	"The Legion invasion events brought infernals crashing down into random zones, causing chaos.",
	"The Lost Isles, the Goblin starting zone, is full of references to pop culture, including Indiana Jones.",
	"The Lost Viking memorial in the Grizzly Hills honors a player who was part of the WoW community and tragically passed away.",
	"The Lost Vikings, a classic Blizzard game, is referenced by NPCs in several WoW locations.",
	"The Lunar Festival holiday event is based on the Chinese New Year.",
	"The Maelstrom is the site of the original Well of Eternity’s destruction.",
	"The Maelstrom was originally planned to be a playable zone in Vanilla WoW but was cut due to technical limitations.",
	"The Maw of Souls dungeon features an elevator that moves fast enough to throw off players who are not paying attention.",
	"The Midsummer Fire Festival celebrates Azeroth’s longest days with bonfires and festive rewards.",
	"The Midsummer Fire Festival celebrates Azeroth’s longest days with bonfires and fireworks.",
	"The Moonkin form for Druids is lovingly called 'Boomkin' by the community.",
	"The Murloc language was created by sound designers gargling water into a microphone.",
	"The NPC 'Haris Pilton' in Shattrath sells a bag named the ‘Gigantique’ as a nod to Paris Hilton’s designer handbags.",
	"The NPC 'Joltan' in Zuldazar is a memorial to a fan who was passionate about World of Warcraft's troll lore.",
	"The NPC Angerforge in Blackrock Depths was renamed to honor a player who passed away and loved that dungeon.",
	"The NPC Chronos in Orgrimmar was created to honor a Blizzard employee who passed away and was deeply involved in the WoW community.",
	"The NPC Haris Pilton in Shattrath City sells a bag called the 'Gigantique,' one of the largest in the game at the time.",
	"The Naaru are beings of pure light, but they can fall into darkness if corrupted.",
	"The Naga were created when Azshara and her followers were transformed by the Old Gods.",
	"The Naxxramas entrance elevator often caused players to fall to their deaths after being resurrected near the raid.",
	"The Netherstorm in Outland is a region torn apart by chaotic arcane energy.",
	"The Nightborne created the magical city of Suramar as a refuge during the Sundering.",
	"The N’Zoth boss fight in Ny’alotha featured mechanics based on Lovecraftian horror.",
	"The Old Gods thrive on corruption and madness, whispering promises of power to mortals.",
	"The Old Gods whisper to players during certain quests and boss fights, often with chilling messages.",
	"The Old Gods whisper to players during certain quests, often sowing doubt and fear.",
	"The Old Gods, like Yogg-Saron and N'Zoth, whisper to players during encounters, with chilling phrases like 'Your heart will explode.'",
	"The Old Gods, such as N'Zoth and Y'Shaarj, thrive on corrupting mortals and driving them insane, often whispering promises of power in exchange for servitude.",
	"The Onyxia Wipe Animation became a viral sensation, based on an actual raid leader’s meltdown.",
	"The Orgrimmar orphanage has NPCs that reference famous WoW lore figures in their playtime activities.",
	"The Oribos elevators in Shadowlands, while not lethal, became a meme for their long wait times compared to the 'deadly' classic elevators.",
	"The Pandaren racial ability ‘Epicurean’ increases the stat boost from food.",
	"The Pandaren racial ability, 'Bouncy,' reduces fall damage by 50%. Pandas are just chill like that.",
	"The Pit of Saron dungeon in Icecrown features Scourge slaves mining saronite, Yogg-Saron’s ‘blood.’",
	"The Pit of Saron dungeon in Icecrown is a frozen mine used by the Scourge.",
	"The Pit of Saron dungeon shows living slaves forced to mine saronite, the blood of Yogg-Saron, until they collapse and die.",
	"The Plaguelands are littered with the remains of entire towns wiped out by the undead plague during the Third War.",
	"The Plaguelands were once a thriving human kingdom before the Scourge wiped it out.",
	"The Plaguelands were once a thriving human kingdom before the undead Scourge devastated it.",
	"The PvP Arena system was introduced in The Burning Crusade expansion.",
	"The PvP title ‘High Warlord’ was one of the hardest titles to earn in Vanilla WoW.",
	"The Reins of the Grey Riding Camel is one of the most difficult mounts to obtain, requiring rare NPC hunting in Uldum.",
	"The Robin memorial in the Warlords of Draenor expansion also includes a nod to Robin Williams’ famous role as Mork with an egg-shaped chair.",
	"The Saronite ore found in Northrend is said to be the blood of Yogg-Saron.",
	"The Scarab Lord title from Ahn'Qiraj is one of the rarest in WoW history.",
	"The Scarlet Crusade believes all non-humans are infected with undeath.",
	"The Scarlet Crusade has some of the most morally questionable NPCs in WoW.",
	"The Scarlet Crusade, a faction devoted to eradicating the undead, often tortures and kills innocent people, believing them to be corrupted by undeath.",
	"The Scarlet Halls dungeon is a training ground for the Scarlet Crusade’s new recruits.",
	"The Scarlet Halls dungeon served as a training ground for new recruits of the Scarlet Crusade.",
	"The Scarlet Monastery was originally planned to be much larger, with multiple wings that never made it to release.",
	"The Scarlet Monastery's dungeon redesign removed its deadly elevator, sparing players from its infamous traps.",
	"The Scarlet Monastery’s leaders were fanatics who thought undeath could be cured.",
	"The Scepter of the Shifting Sands questline is one of the longest and most epic in WoW history.",
	"The Scourge necropolises were massive death factories, designed to harvest and reanimate the fallen en masse.",
	"The Scourge's necropolises were designed to harvest and reanimate the dead on an industrial scale, turning entire populations into undead armies.",
	"The Sha of Pandaria represent negative emotions like anger, fear, and doubt.",
	"The Sholazar Basin in Northrend was inspired by the Un’Goro Crater in Kalimdor.",
	"The Shrine of the Fallen Warrior in the Barrens was created to honor a Blizzard employee who passed away during WoW's development.",
	"The Siege of Orgrimmar raid marked the end of Garrosh Hellscream’s reign as Warchief.",
	"The Silithid race in WoW is inspired by the insect-like Zerg from StarCraft.",
	"The Spire of Ascension in Shadowlands introduced another deadly elevator, with players often falling while trying to shortcut their way down.",
	"The Storm Peaks zone is heavily inspired by Nordic mythology and landscapes.",
	"The Stormwind park district was destroyed in Cataclysm and only rebuilt years later.",
	"The Sword of a Thousand Truths from South Park was inspired by in-game legendary items.",
	"The TCG loot card 'Spectral Tiger' is still one of the most sought-after mounts in WoW.",
	"The Tauren capital, Thunder Bluff, is built on giant mesas for protection against enemies.",
	"The Timbermaw Hold faction in Felwood has some of the hardest-to-please furbolgs in the game.",
	"The Timbermaw Hold tunnels connect Felwood, Winterspring, and Moonglade.",
	"The Time-Lost Proto-Drake is one of the rarest and most sought-after mounts in World of Warcraft.",
	"The Timeless Isle features unique items that transform players into frogs, birds, or other animals.",
	"The Timeless Isle has an unmarked cave where you can find ancient Pandaren scrolls detailing lost lore.",
	"The Timeless Isle in Pandaria has a mysterious shrine where you can ask for fortunes.",
	"The Timeless Isle in Pandaria is filled with Easter eggs, including a giant rubber ducky.",
	"The Timeless Isle in Pandaria is filled with random events, rare mobs, and unique collectibles.",
	"The Timeless Isle is filled with random events, including a mysterious ghost ship.",
	"The Tiny Green Ragdoll toy in Warlords of Draenor was designed by a Blizzard employee as a gift for their child.",
	"The Tiny Green Ragdoll toy is one of the creepiest items you can place in your Garrison.",
	"The Titans shaped Azeroth's continents by moving massive mountain ranges with their colossal strength.",
	"The Turtle Mount is a rare fishing drop and was one of the first mounts added via fishing.",
	"The Tuskarr fishing villages in Northrend have some of the coziest vibes in the game.",
	"The Tuskarr of Northrend are known for their fishing skills and intricate carvings.",
	"The Undercity was built within the ruins of Lordaeron's capital, where the Forsaken rule amid the remnants of Arthas' betrayal and genocide.",
	"The Un’Goro Crater in Kalimdor is inspired by real-life prehistoric locations like the Galápagos Islands.",
	"The Void Elf starting zone has an inaccessible tower with Void crystals that pulse with unknown energy.",
	"The Void Elves were exiled Blood Elves who embraced the void for power.",
	"The Void Elves were once Blood Elves who embraced the Void for its forbidden power.",
	"The Void whispers to anyone who taps into its power, driving weaker minds to madness with promises of infinite knowledge.",
	"The Vrykul in Howling Fjord believe their dead warriors ascend to Valhalla, but no direct lore confirms this afterlife exists.",
	"The Vrykul of Northrend believe only the strongest warriors deserve to ascend to Valhalla.",
	"The Vrykul were originally intended to be a playable race in Wrath of the Lich King.",
	"The Wailing Caverns dungeon emits faint, ghostly wails, allegedly the spirits of those trapped in the caverns.",
	"The Wailing Caverns was originally going to be a solo dungeon.",
	"The Wailing Caverns, a low-level dungeon, hides the twisted experiments of Druids of the Fang, who sought to corrupt nature itself.",
	"The Wand of Animation lets you bring objects to life. Some players use it for mischief.",
	"The Wandering Isle, the Pandaren starting zone, is a giant turtle named Shen-zin Su.",
	"The Wandering Isle, the Pandaren starting zone, is carried on the back of a giant turtle.",
	"The Wandering Isle’s name refers to the fact that it floats and travels across the ocean.",
	"The War of the Ancients began when Queen Azshara and her Highborne attempted to summon Sargeras to Azeroth, leading to untold death and destruction.",
	"The War of the Ancients began when Queen Azshara attempted to summon Sargeras to Azeroth.",
	"The Well of Eternity’s explosion reshaped Azeroth into the continents we know today, creating the Maelstrom at its center.",
	"The Whispering Forest event includes eerie faerie dragons performing rituals in the dead of night, with no explanation given in the game.",
	"The Whispering Forest in Tirisfal Glades is home to a ritual where faerie dragons gather to perform a haunting, otherworldly ceremony.",
	"The Wind Rider mounts used by the Horde are inspired by lions with bat wings.",
	"The Worgen curse originated from a druidic ritual gone wrong.",
	"The Wrathgate betrayal in Wrath of the Lich King marked one of WoW’s darkest lore moments.",
	"The Wrathgate betrayal saw the Forsaken unleash a plague that melted Horde and Alliance forces alive, leaving piles of steaming corpses.",
	"The Wrathgate cinematic depicts one of the darkest betrayals in WoW history, where Putress and the Forsaken unleash a plague, killing Alliance, Horde, and Scourge forces indiscriminately.",
	"The Wrathion NPC in Mists of Pandaria is one of the last uncorrupted Black Dragons.",
	"The Zandalari Trolls' Loa gods are based on real-world voodoo and spiritual traditions.",
	"The Zandalari Trolls’ Dazar'alor temple is one of the tallest structures in WoW.",
	"The Zandalari Trolls’ empire predates the Sundering and the splitting of Azeroth into continents.",
	"The Zandalari empire predates the Night Elves’ civilization, making it one of the oldest in Azeroth’s history.",
	"The Zhevra Plains in the Barrens are home to herds of unique striped creatures.",
	"The Zhevras in the Barrens are based on zebras but have unique horns.",
	"The chain quest for the Scepter of the Shifting Sands in Silithus is one of the longest and most complex questlines in WoW history.",
	"The city of Dalaran has moved multiple times in Azeroth’s history, most recently to the Broken Isles.",
	"The city of Dalaran has moved three times in WoW’s history.",
	"The city of Suramar in Legion is based on the height of Nightborne civilization.",
	"The cursed blade Frostmourne consumed the souls of those it killed and enslaved its wielder to the Lich King’s will.",
	"The cursed blade Frostmourne consumed the souls of those it killed, enslaving their spirits for eternity.",
	"The cursed pirate fleet of Helya in Stormheim is composed of souls she captured and bound to her service, denying them peace in the afterlife.",
	"The daily fishing quest in Dalaran, 'Disarmed!', has players fish up a severed arm holding a sword.",
	"The dance for male Trolls is based on Michael Jackson's 'Thriller.'",
	"The dungeon Scholomance is named after a legendary school of black magic from folklore.",
	"The dungeon Scholomance was once a secret academy for necromancers under Kel’Thuzad’s command.",
	"The elevator in Dazar’alor occasionally 'bugged,' causing players to fall through it and die in the process.",
	"The elevator in Hellfire Citadel became a meme in the community for how often it claimed the lives of rushing raiders.",
	"The elevator in Icecrown Citadel, while not as infamous, still managed to snag players in a hurry to reach the next boss.",
	"The elevator in Serpentshrine Cavern became notorious for wiping groups when players fell off during attempts to avoid trash mobs.",
	"The elevator in The Nexus dungeon seems harmless but still managed to trip up players who underestimated its speed.",
	"The elevator in Ulduar, leading to the Antechamber, has caused countless deaths as players raced to board or dismounted too late.",
	"The first level 60 player in Vanilla WoW took about 10 days of /played time.",
	"The first player to hit max level in WoW Classic did it by grinding mobs for days straight.",
	"The first player to reach level 60 in WoW Classic did it by grinding mobs non-stop for days.",
	"The first raid boss in WoW, Onyxia, has over 50 voice lines to taunt players.",
	"The first raid, Molten Core, required players to farm resistance gear to survive the fights.",
	"The first world-first raid boss kill was Ragnaros in Molten Core.",
	"The fishing artifact Underlight Angler allows players to walk on water and breathe underwater.",
	"The fishing chair toy lets players sit while fishing, adding flavor to the profession.",
	"The fishing loot table in Zangarmarsh includes a rare chance to fish up a weapon called ‘Mudfish Sword.’",
	"The game still references Kael'thas Sunstrider's infamous line, 'Tempest Keep was merely a setback!'",
	"The game’s launch included only 8 races, with the Draenei and Blood Elves added in The Burning Crusade.",
	"The game’s original developers hid jokes in item tooltips, like 'This sword doesn’t actually exist.'",
	"The game’s original developers used to run events on live servers disguised as NPCs.",
	"The ghost of an unnamed Blood Elf prince can occasionally be seen in Silvermoon City, wandering the ruins.",
	"The giant skeleton in the Shimmering Flats may be the remains of a titan or an Old God’s minion, though Blizzard has never confirmed it.",
	"The giant trees in Ashenvale are thousands of years old and protected by the Night Elves.",
	"The goblins' obsession with explosives has caused more than one in-game accident.",
	"The haunted Karazhan crypts, a location originally cut from the game, contain chilling areas like the 'Upside-Down Sinners,' where corpses float eerily underwater.",
	"The haunted inn in Goldshire (on some servers) has a second floor where children appear at night in a pentagram formation.",
	"The haunted manor in Drustvar is filled with ghostly whispers and objects that move on their own, hinting at the Heartsbane Coven's dark magic.",
	"The infamous 'Barrens Chat' became a community meme due to its random and chaotic discussions.",
	"The infamous 'Barrens Chat' was where most Chuck Norris jokes were born in WoW.",
	"The infamous Corrupted Blood incident became a case study for epidemiologists.",
	"The legendary Thunderfury sword was often memed in trade chat as 'Thunderfury, Blessed Blade of the Windseeker.'",
	"The legendary cloak questline in Mists of Pandaria required weeks of grinding to complete.",
	"The legendary questline in Mists of Pandaria required players to gather Sigils of Power and Wisdom, leading to a cinematic featuring Wrathion.",
	"The legendary weapon Sulfuras was inspired by Norse mythology’s hammer of the gods.",
	"The loading screen tips have a 0.01% chance to display 'You are not prepared!' as a joke.",
	"The maximum level in Vanilla WoW was 60, and reaching it could take weeks of gameplay.",
	"The model for Gnomish Engineers’ devices was inspired by old steampunk aesthetics.",
	"The model for Gnomish Engineers’ gadgets was inspired by steampunk aesthetics.",
	"The most expensive mount in WoW history is the Mighty Caravan Brutosaur, aka the 'Longboi.'",
	"The most infamous quest in Vanilla was 'Deep Ocean, Vast Sea'—because no one had water breathing.",
	"The mount ‘Big Love Rocket’ is one of the rarest in-game items, only available during Love is in the Air.",
	"The mount ‘Invincible’ is named after Arthas’ loyal steed, who died before his transformation into the Lich King.",
	"The mount ‘Reins of the Traveler’s Tundra Mammoth’ includes vendors that sell and repair items.",
	"The mount ‘Sky Golem’ allows players to harvest herbs without dismounting.",
	"The music in Grizzly Hills is so beloved that it’s often played outside the game.",
	"The music in Storm Peaks is inspired by Nordic mythology and landscapes.",
	"The neutral Pandaren starting zone is technically a giant turtle named Shen-zin Su.",
	"The original AQ War Effort event required entire servers to work together to unlock the raid.",
	"The original Dark Portal event caused crashes when too many players showed up.",
	"The original Naxxramas raid had bosses so hard that most guilds never finished it.",
	"The original WoW Alpha featured a zone called 'Dragon Isles' that wasn’t released until Dragonflight.",
	"The original WoW Alpha included fully functional flying mounts, but they were removed for Vanilla.",
	"The original WoW had no in-game map markers, forcing players to rely on memory or third-party guides.",
	"The original WoW release featured only two continents: Kalimdor and the Eastern Kingdoms.",
	"The original design for Death Knights in Vanilla WoW was an alternate hero class that started at level 1.",
	"The original talent trees in Vanilla WoW offered players deep customization but had many 'trap' builds.",
	"The pandas in Valley of the Four Winds sometimes wave at you if you emote back.",
	"The pet Pepe has costumes for different in-game holidays, including a pirate hat!",
	"The quest 'A Simple Re-Quest' requires players to return the same item to the same NPC repeatedly for a humorous reward.",
	"The quest 'Aberrations of Bone' in Maldraxxus lets players create an undead army to battle enemy forces.",
	"The quest 'Aiding the Alliance' in Vanilla WoW was so long and grindy that players joked it should give a free mount.",
	"The quest 'An Escaped Troll' in Vanilla WoW was bugged for years, making it impossible to complete until it was quietly fixed.",
	"The quest 'Blown Away' in Valley of the Four Winds has players chasing after rolling bundles of escaped grain.",
	"The quest 'For the Horde!' lets players infiltrate enemy cities to claim the heads of faction leaders, creating legendary PvP battles.",
	"The quest 'Gnomebliteration' in Uldum lets players control a giant ball of fire to roll over thousands of gnomes.",
	"The quest 'Help Tavara' in Azuremyst Isle is one of the first quests to highlight the plight of the Draenei after their crash landing.",
	"The quest 'It’s a Trap!' in Icecrown Citadel is a playful nod to Admiral Ackbar’s famous line from Star Wars.",
	"The quest 'Love is in the Air' during the Valentine's event has players uncover a sinister plot behind the Crown Chemical Company.",
	"The quest 'Raptors Unleashed' in Un'Goro Crater is inspired by Jurassic Park, with playful nods to dinosaur chaos.",
	"The quest 'Shaving Supplies' in Zangarmarsh is a nod to the fact that no one can imagine a Naga needing shaving cream.",
	"The quest 'The Day Deathwing Came' in the Badlands features hilarious stories told by NPCs exaggerating their encounters with Deathwing.",
	"The quest 'The Escape from Durnholde' in the Caverns of Time lets players travel back in time to free Thrall from captivity.",
	"The quest 'The Fate of Val’sharah' in Legion features a tragic cinematic involving Ysera, a beloved dragon aspect.",
	"The quest 'The Last Relic of Argus' takes players across multiple continents in a scavenger hunt for Draenei artifacts.",
	"The quest 'The Legend of Stalvan' in Duskwood reveals a chilling tale of murder and madness tied to a cursed family heirloom.",
	"The quest 'The Littlest Mountain' in Cataclysm has players collect items for a tiny mountain golem companion.",
	"The quest 'The Stoppable Force' in Northrend pokes fun at the classic joke about an unstoppable force meeting an immovable object.",
	"The quest 'They Grow Up So Fast' in the Barrens lets players raise a Venomhide Ravasaur from hatchling to mount.",
	"The quest 'To All the Squirrels I've Loved Before' encourages players to /love small critters across Azeroth.",
	"The quest 'Welcome to the Machine' in Hillsbrad Foothills turns the tables by having players act as a quest giver to hilarious NPC adventurers.",
	"The questline for the legendary weapon Atiesh required months of raiding and dedication.",
	"The questline to obtain the legendary weapon Atiesh required raiding and months of dedication.",
	"The rare spawn Loque’nahak in Sholazar Basin is a Spirit Beast highly prized by hunters.",
	"The sword 'Ashbringer' was teased for years before finally being added in Wrath of the Lich King.",
	"The term 'Leeroy Jenkins' is now officially in the Merriam-Webster dictionary as a meme.",
	"The term 'Void' in WoW refers to a dark, shadowy power that opposes the Light.",
	"The title 'Salty' can be earned by completing the most difficult fishing achievements in WoW.",
	"The title 'Salty' is awarded to players who complete the most challenging fishing achievements.",
	"The town of Goldshire is infamous on certain RP servers for… unconventional activities.",
	"The toy 'Piccolo of the Flaming Fire' makes everyone nearby dance. Perfect for raid trolling.",
	"The toy 'Wand of Simulated Life' lets players bring inanimate objects to life temporarily.",
	"The toy Ethereal Soul-Trader summons a vendor from another dimension who trades unique items.",
	"The toy Gnomish X-Ray Specs allows players to see everyone around them as skeletons.",
	"The toy ‘Ethereal Soul-Trader’ lets players summon a vendor from another dimension.",
	"The toy ‘Fishing Chair’ allows players to sit while fishing, adding flavor to the profession.",
	"The toy ‘Piccolo of the Flaming Fire’ forces everyone nearby to dance.",
	"The toy ‘Robo-Gnomebulator’ temporarily turns players into gnomish robots.",
	"The toy ‘Sack of Starfish’ summons flying starfish to follow players around.",
	"The toy ‘Super Simian Sphere’ transforms players into a glowing ape inside a magical bubble.",
	"The troll city of Zul’Gurub was once a raid but is now a 5-player dungeon.",
	"The underwater ruins in Vashj'ir are inhabited by naga and feature skeletal remains of creatures never identified by lore.",
	"The underwater ruins in Vashj’ir are filled with ancient Kaldorei architecture that predates the Sundering.",
	"The underwater ruins in Vashj’ir were once part of a thriving Kaldorei empire.",
	"The underwater ruins of Vashj'ir are remnants of an ancient Naga empire.",
	"The underwater zone Nazjatar was ruled by Queen Azshara for millennia.",
	"The underwater zone Vashj’ir was Blizzard’s first fully aquatic environment.",
	"The whispering trees in Ashenvale occasionally emit faint words about the Old Gods’ influence.",
	"The zone Winterspring is known for its pristine snow and rare Frostsaber mounts.",
	"The zone Winterspring is known for its pristine snow and rare Frostsaber mounts.",
	"There's a gnome NPC in Northrend who complains about how cold it is—he's not wrong.",
	"There's a legendary trinket called 'The Skull of Gul'dan,' but Gul'dan isn't amused.",
	"There's a rare mount in Nazjatar that drops from a crab called 'Snapdragon.'",
	"There's a secret fishing spot in Booty Bay that increases your chance for rare catches.",
	"There's a secret pet in the game called 'Mr. Bigglesworth' that references Naxxramas' boss Kel'Thuzad.",
	"There's a secret underwater cave in Zangarmarsh with glowing mushrooms.",
	"There's a turtle NPC named Lvl ?? Elite who is a parody of TMNT in Pandaria.",
	"There’s a Murloc NPC in Northrend who has a small quest chain that reveals he’s trying to learn Common to communicate with adventurers.",
	"There’s a faint outline of a dragon etched into the mountains of Storm Peaks, hinting at a cut piece of content.",
	"There’s a giant skeleton in the Shimmering Flats that might belong to a forgotten titan.",
	"There’s a gnome NPC in Gnomeregan who complains about the radiation being 'totally safe.'",
	"There’s a gnome NPC in the Brawler’s Guild who references the Rocky movies.",
	"There’s a graveyard in Duskwood with headstones that tell jokes if you read them.",
	"There’s a hidden NPC named Captain Placeholder that used to stand in for unfinished content.",
	"There’s a hidden cave in Azshara where developers left untextured walls as an inside joke.",
	"There’s a hidden cave in the Badlands filled with skeletons and treasure maps.",
	"There’s a hidden crypt in Karazhan called the 'Upside-Down Sinners,' featuring chained corpses floating underwater.",
	"There’s a hidden panda NPC in Pandaria who offers wise advice and riddles.",
	"There’s a hidden tribute to Robin Williams in Draenor: a genie NPC called 'Robin.'",
	"There’s a hidden tribute to StarCraft in Azshara, with zergling-like creatures near the shoreline.",
	"There’s a hidden underwater cave in Vashj’ir filled with glowing jellyfish.",
	"There’s a hidden vendor in Azshara who sells items with no practical use, such as 'Ethereal Socks.'",
	"There’s a miniature version of Stormwind Keep hidden in the Deeprun Tram tunnel.",
	"There’s a rare fish in Stranglethorn Vale called the Dezian Queenfish that’s purely decorative.",
	"There’s a rare gnome in Borean Tundra who rides a mechanical spider mount.",
	"There’s a rare mob called 'The Rake' that became famous for being the best Hunter pet in Classic WoW.",
	"There’s a rare mob in the Jade Forest that has a pet panda named after a Blizzard employee.",
	"There’s a rare spawn in Tanaris called Caliph Scorpidsting. He drops a scorpion that isn’t even a pet.",
	"There’s a rare spawn named 'Time-Lost Proto-Drake' that hunters have searched for years to tame.",
	"There’s a rare vanity pet called 'Bananas' that’s a baby monkey wearing a diaper.",
	"There’s a secret bar hidden in Booty Bay where NPCs argue over pirate treasure.",
	"There’s a secret chicken farm in Hillsbrad Foothills where chickens wander free.",
	"There’s a secret hatch in Uldum referencing the TV show Lost.",
	"There’s a secret location in Icecrown where a ghostly mage trains forever in solitude.",
	"There’s a secret tribute to a Blizzard employee in the Storm Peaks, featuring their favorite pet.",
	"There’s a toy called the 'Disco Ball' that turns every nearby player into a dancer.",
	"There’s a waterfall in Pandaria that has a hidden cave with an abandoned tea set.",
	"There’s an unused arena in Stranglethorn Vale called the 'Fang Arena' that was planned for PvP content.",
	"Throne of Thunder introduced another deadly elevator boss, with players frequently falling to their deaths after Durumu the Forgotten.",
	"Tier sets for classes in Vanilla WoW were obtained from raids, creating intense competition for drops.",
	"Undercity’s throne room still bears scorch marks from the Wrathgate betrayal.",
	"Vanilla WoW had no in-game map markers. You just had to remember where stuff was.",
	"Vanilla WoW had no transmog system, and players had to deal with mismatched armor sets.",
	"Vanilla WoW required players to spend gold to learn new abilities, which became expensive at higher levels.",
	"Wandering traders in Pandaria occasionally offer rare items, but their locations are never fixed.",
	"Warlocks in Vanilla were so OP that guilds demanded you level one for raids.",
	"When World of Warcraft first launched, players had to queue for hours to log in due to server overloads.",
	"Worgen used to be a part of the Scythe of Elune storyline before they became playable.",
	"World PvP objectives like the battles in Hillsbrad Foothills became iconic pre-Battleground activities.",
	"World of Warcraft launched on November 23, 2004, the 10th anniversary of the Warcraft franchise.",
	"World of Warcraft's original box art featured a Night Elf female and a male Orc.",
	"Yogg-Saron claims responsibility for Deathwing's madness, whispering, 'He was merely a puppet. All were puppets.'",
	"Yogg-Saron, the Old God imprisoned in Ulduar, whispers maddening secrets to players, claiming to have influenced Deathwing and other major events in Azeroth's history.",
	"You can find NPCs in Azeroth arguing about which came first, the murloc or the egg.",
	"You can find NPCs in Dalaran who look suspiciously like Harry Potter characters.",
	"You can find a broken statue of Arthas hidden in Icecrown, symbolizing his tragic fall.",
	"You can find a penguin pet in Northrend that waddles around without a care in the world.",
	"You can find a rare chicken in Elwynn Forest that starts a hidden quest if you /chicken at it.",
	"You can find a small shrine to Uther the Lightbringer in the Plaguelands.",
	"You can find a small tribute to StarCraft inside the Engineering profession.",
	"You can find an NPC named 'Haris Pilton' selling overpriced bags as a parody of Paris Hilton.",
	"You can find an NPC named 'Ron Burgundy' in Dalaran who references the movie 'Anchorman.'",
	"You can find penguins in Northrend who will slide down icy slopes if you wait long enough.",
	"You can find the remains of a crashed goblin airship in Azshara.",
	"You can sometimes hear NPCs gossiping about players in inns if you stand close enough.",
	"You can still find remains of Old God minions buried deep within Silithus.",
	"You can unlock secret dialogues with certain NPCs by using specific emotes like /salute or /cheer.",
	"Zul’Gurub introduced the first raid-wide debuff mechanics, challenging players to think strategically.",
	"Zul’Gurub's 'spinning elevator' in the original raid design would disorient players, leading to falls into the water below.",
}
