local _, namespace = ...

-- Fact List
namespace.factslist = {
	"A Tauren NPC in Thunder Bluff plays a flute version of 'My Heart Will Go On' by Celine Dion.",
	"A bug in Vanilla WoW once allowed hunters to tame boss-level mobs.",
	"A fish in Pandaria has the name 'Wish-Fish' and drops a wish-granting item... sometimes.",
	"A hidden NPC in Stranglethorn Vale sells bananas to players. Why? No one knows.",
	"A hidden NPC in the Grizzly Hills serenades players with a fishing song.",
	"A hidden Pandaren NPC brews tea in the Jade Forest and offers it to passing players.",
	"A hidden vendor in Winterspring sells a pattern for a Frostsaber mount.",
	"A quest in the Barrens involves investigating why kodos mysteriously vanish into the desert.",
	"A rare toy called the 'Flame Eater' lets you breathe fire on other players.",
	"An NPC in Booty Bay references the Pirates of the Caribbean movie franchise.",
	"An NPC in Dalaran tells players he’s been polymorphed into a sheep for years.",
	"An NPC in Nagrand references the famous line ‘This is not my beautiful house!’ from the Talking Heads song.",
	"Arakkoa from Outland were originally guardians of the Apexis Crystals.",
	"Arthas’ horse, Invincible, is one of the most sought-after mounts in the game.",
	"Before mounts, players used to joke that Druids had the first 'vehicle'—Travel Form.",
	"Blizzard developers used to host trivia contests during in-game events.",
	"Blizzard once added a 'Dance Studio' in patch notes as an April Fool’s joke.",
	"Blizzard once added a toy that spawns a tiny disco floor for everyone to dance on.",
	"Blizzard once hid an NPC named Jon in Shadowmoon Valley as a tribute to a long-time player.",
	"Blizzard once hosted an in-game memorial for a player who passed away.",
	"Blizzard once released a patch that accidentally made hunters' pets invincible in PvP.",
	"Blizzard once turned a player’s cat into an in-game NPC as a memorial.",
	"Darkmoon Faire NPCs have some of the creepiest dialogue in the game. Read it closely.",
	"Death Knights start at level 55 because lore-wise, they 'skipped' normal life. Convenient!",
	"Did you know that Thrall’s name means 'slave' in Old Norse?",
	"Draenei crystals are infused with holy energy, which makes them glow.",
	"Draenei spaceships are powered by magic crystals called Naaru cores.",
	"During Brewfest, players can complete a quest that involves riding a ram and stealing kegs.",
	"During Brewfest, players can earn a ‘Brewmaster’ title by completing seasonal achievements.",
	"During Brewfest, players can fight a boss named Coren Direbrew to earn unique mounts.",
	"During Children’s Week, you can take orphans on adventures across Azeroth.",
	"During Hallow’s End, you can trick-or-treat for rare items and spooky rewards.",
	"During Legion, Demon Hunters could double-jump, making them the most agile class in the game.",
	"During Legion, players could obtain a fishing artifact called the ‘Underlight Angler.’",
	"During Wrath pre-patch events, the zombie plague could completely wipe out entire cities.",
	"During Wrath pre-patch events, zombie infections could spread across entire cities.",
	"During the Cataclysm, Deathwing scarred Azeroth permanently with massive earthquakes.",
	"During the Cataclysm, most players forgot about Gilneas after leveling through it.",
	"During the MoP expansion, the Tillers farm was a hidden favorite for casual players.",
	"During the WoW beta, Mages could teleport other players... anywhere. Chaos ensued.",
	"During the pre-Wrath zombie plague event, players infected with a zombie virus could spread it, turning entire cities into chaos.",
	"Each expansion of WoW introduced at least one major lore character as a raid boss.",
	"Every playable class in WoW has at least one spell inspired by Dungeons & Dragons mechanics.",
	"Forsaken Apothecaries create plague experiments using unwilling test subjects, some of whom are still alive.",
	"Frost Mages used to kite raid bosses indefinitely during glitches. Blizzard patched it out.",
	"Frost Mages were nicknamed 'ice cannons' for their powerful crowd control abilities in PvP.",
	"Gnomes used to have a racial ability called 'Escape Artist' that was great in PvP.",
	"Gnomes were added as a playable race partly as comic relief for the Alliance.",
	"Goblin engineering is so volatile that early WoW players blew themselves up crafting items!",
	"Goblins are known for their explosive mining techniques, which sometimes backfire spectacularly.",
	"Goblins are the only race in WoW to have their own functional rocket transport network.",
	"Goblins have a secret motto: 'Time is money, friend!' It’s not so secret anymore.",
	"Goblins invented rockets, but they never patented them. That’s why everyone uses them.",
	"Goblins used to explode their own mounts for fun before it was patched out.",
	"Goblins were added as a playable race because of their popularity as quirky NPCs.",
	"Gryphons were first introduced as Alliance mounts in Warcraft II.",
	"Helya’s Kvaldir pirates are bound to her will and doomed to wander the seas for eternity, never finding rest.",
	"Hogger is so infamous that he has his own raid encounter in the Hearthstone game.",
	"Hogger, a low-level gnoll in Elwynn Forest, became a meme as one of the deadliest starter mobs.",
	"Hunters used to have to feed their pets regularly to keep them happy, or they’d run away.",
	"Hunters used to need ammunition to shoot their ranged weapons, taking up bag space.",
	"If you /wave at certain NPCs, they will wave back. Try it on a guard!",
	"If you duel in the Gurubashi Arena, everyone can loot your corpse if you die.",
	"If you jump enough times as a Gnome, other players might ask you to stop. It’s too cute.",
	"If you spam the /moo emote as a Tauren, sometimes you get a special response.",
	"If you swim far enough out to sea, fatigue will kill you faster than any shark can.",
	"In Ashenvale, players can find ancient ruins of the Night Elves' first cities.",
	"In Azeroth, all female Draenei canonically wear high heels. Always ready for a party.",
	"In Classic WoW, it could take weeks to gather enough materials for a single raid attempt.",
	"In Classic WoW, players had to manually discover flight paths by visiting them in person.",
	"In Classic WoW, rogues could vanish mid-battle, confusing raid bosses completely.",
	"In Dalaran, there’s a vendor who sells cheese that’s 'aged for a millennium.' Expensive, though.",
	"In Deadwind Pass, players report hearing unsettling noises while exploring the area around Karazhan.",
	"In Draenor, you can fish up a shark mount called the ‘Riding Shark.’",
	"In Drustvar, players uncover evidence of witchcraft, dark rituals, and human sacrifices performed by the Heartsbane Coven.",
	"In Icecrown Citadel, players encounter tortured souls begging for release, their cries echoing through the halls of the Scourge’s stronghold.",
	"In Icecrown Citadel, you encounter tortured souls begging for release, including those trapped in weapons like the Shadowmourne axe.",
	"In Karazhan, there's an upside-down room where gravity clearly doesn't exist.",
	"In Legion, NPCs sometimes broke the fourth wall and commented on how many heroes exist.",
	"In Legion, players could loot hidden artifact appearances by solving puzzles.",
	"In Legion, players could solo older raids and collect every artifact appearance.",
	"In Maldraxxus, failed creations and broken souls are discarded into heaps, left to rot or be consumed by stronger beings.",
	"In Maldraxxus, souls deemed unworthy are broken down into anima, essentially consuming their essence for power.",
	"In Maldraxxus, the House of Eyes trained the most skilled spies in the Shadowlands.",
	"In Mechagon, you can build your own customizable mechanical mounts.",
	"In Moonglade, you can find a giant turtle that’s over 10,000 years old.",
	"In Moonglade, you can find ancient trees with faces carved into their bark.",
	"In Northrend, you can find skeletal remains of ancient sea monsters washed ashore.",
	"In Orgrimmar, the Auction House has secret goblin tunnels connecting different areas.",
	"In Outland, some NPCs still reference the Burning Crusade as if it’s happening right now.",
	"In Outland, you can find an NPC named 'Haris Pilton' selling overpriced bags. Yes, that's a joke.",
	"In Pandaria, the Hozen view time differently, calling the past ‘yesterday’ and the future ‘long yesterday.’",
	"In Pandaria, you can find a hidden shrine dedicated to a cat named Socks.",
	"In Revendreth, the souls of sinners are dragged into cages and drained of anima, their screams filling the air.",
	"In Scholomance, students of necromancy dissect corpses in the name of dark magic and reanimation.",
	"In Shadowlands, Revendreth is a realm for sinful souls to atone, but many are tortured endlessly for their misdeeds rather than redeemed.",
	"In Shadowmoon Valley, ghostly orcs can still be seen performing their ancient rituals.",
	"In Silverpine Forest, Forsaken forces desecrate graves and raise fallen humans into undeath, regardless of their wishes in life.",
	"In Silverpine Forest, Forsaken grave robbers desecrate human burial sites, raising the dead as unwilling soldiers.",
	"In Tirisfal Glades, the dead sometimes rise on their own, wandering aimlessly as restless spirits.",
	"In Vanilla WoW, you had to craft resistance gear to survive certain raid encounters.",
	"In Vanilla, people spent hours farming for rare mounts like the Baron Rivendare's Deathcharger.",
	"In Winterspring, you can still find NPCs referencing the epic Wintersaber grind.",
	"In WoW Classic, players had to carry quivers for arrows or they couldn’t attack as Hunters.",
	"In WoW, chickens are smarter than they look. There's a secret questline if you /chicken at one!",
	"In Wrath of the Lich King, players could accidentally kite raid bosses into Dalaran, causing chaos.",
	"In Wrath of the Lich King, players could duel on the edges of Dalaran and knock each other off.",
	"In Zandalar, the Blood Trolls worship the Blood God G’huun, an artificial Old God.",
	"In early WoW, jumping off Thunder Bluff accidentally was a rite of passage for Taurens.",
	"In early WoW, players used to sit around campfires for no reason other than vibes.",
	"In the Barrens, there's a neutral Kodo skeleton NPC named 'Old Blanchy’s Cousin.'",
	"In the Barrens, you can find a mysterious oasis guarded by aggressive creatures.",
	"In the Battle for Azeroth expansion, you can find NPCs making fun of previous expansions’ plot holes.",
	"In the Howling Fjord, vrykul warriors believe dying in battle earns them a place in Valhalla.",
	"In the Scarlet Monastery, fanatical crusaders burn people alive, believing it purifies their souls from undeath.",
	"In the Shadowlands, souls who fail their trials are thrown into the Maw, where they suffer eternal torment and oblivion.",
	"In the Whispering Forest of Tirisfal Glades, faerie dragons perform a haunting ritual surrounded by eerie whispers and glowing light.",
	"In the Wrath pre-patch, the zombie plague turned every player into a griefing machine.",
	"In the original WoW beta, Dwarves could play as Mages, but it was removed before launch.",
	"In the original WoW beta, players could kill quest-giving NPCs, breaking quests for everyone.",
	"Kel'Thuzad, the lich and servant of the Lich King, was a former mage of Dalaran who willingly embraced necromancy and helped spread the plague of undeath.",
	"Khadgar’s beard is so iconic that players often joke about him hiding magic items in it.",
	"Kkthnx made this addon so he could procrastinate updating his alts’ gear.",
	"Kkthnx, creator of KkthnxUI and WTFacts, is probably coding this addon while standing in the Auction House.",
	"Kkthnx, the brains behind this addon, has written more lines of code than he’s run dungeons. Priorities.",
	"Kkthnx, the genius behind KkthnxUI, made this addon because Azeroth can always use more random facts.",
	"Mages in early WoW used to make a killing selling food and water to players.",
	"Mages were the first class to have teleportation spells for instant travel.",
	"Mechagnomes were introduced in Battle for Azeroth as a playable race for the Alliance.",
	"Mount Hyjal was inaccessible in Vanilla but had a hidden entrance that players exploited.",
	"Murlocs have a higher chance to drop green items than most other mobs in the game.",
	"Murlocs have their own language, but no one has successfully translated it—yet.",
	"Murlocs were added to Warcraft lore late in development because devs wanted 'something weirder.'",
	"Naga were once Night Elves, transformed after the Well of Eternity exploded.",
	"Players can find a friendly murloc named Murky, Blizzard’s first official murloc mascot.",
	"Players in Classic WoW created 'bridges' by standing on each other to reach secret places.",
	"Players in early WoW loved to kite world bosses into major cities for laughs... and mass deaths.",
	"Players in early WoW would duel in front of Stormwind for hours, betting gold on matches.",
	"Players who complete 'Insane in the Membrane' earn one of the hardest titles in the game.",
	"Players who earn the title 'The Insane' must max out reputations with factions that despise each other.",
	"Rogues in Vanilla WoW could pickpocket unique items like lockboxes and junk.",
	"Rogues in Vanilla could one-shot people using Ambush if they stacked enough Agility.",
	"Shaman totems once had to be placed individually—and they could be destroyed by enemies.",
	"Some Forsaken NPCs in Tirisfal Glades still wear the armor they died in.",
	"Some Forsaken NPCs still reference their human lives in odd and unsettling ways.",
	"Some Murlocs in Elwynn Forest wear fishing hats, suggesting they’ve adapted to human habits.",
	"Some Night Elf ruins in Azeroth still hold ancient moonwell water with magical properties.",
	"Some Tauren NPCs reference the phrase 'bull market,' a nod to financial humor.",
	"Some Tauren totems in Thunder Bluff are carved with stories of their ancestors’ bravery.",
	"Some WoW zones like Azshara were originally supposed to be major cities but were scrapped.",
	"Some bosses in raids will taunt players by using their own voice lines against them.",
	"Some early raid bosses used to have unlootable corpses if players killed them incorrectly.",
	"Some fishing spots in Azeroth are so rare they only appear during in-game weather events.",
	"Some mobs in WoW Classic dropped gray items with hilariously long names just for fun.",
	"Some of the NPCs in Booty Bay are named after pirates from real history.",
	"Some of the Zandalari Trolls’ architecture predates the Sundering of Azeroth.",
	"Some of the goblin trade cartels engage in piracy, rivaling traditional ships on the seas.",
	"Some of the jokes told by Troll NPCs in the game are puns on real-world Rastafarian culture.",
	"Some of the worgen NPCs in Gilneas quote lines from Victorian literature.",
	"Some rare creatures in Azeroth drop vanity items, like hats, glasses, and even cosmetic swords.",
	"Some rare mobs drop vanity items like cooking hats or pirate costumes.",
	"Some rare spawns in Northrend drop vanity pets instead of gear or crafting materials.",
	"Tauren totems are carved with symbols that tell their tribe’s history.",
	"Teldrassil, the World Tree, was corrupted by an Old God shortly after it was grown.",
	"The 'Dancing Troll Village' is a hidden zone with NPCs partying 24/7. It's amazing.",
	"The 'Disgusting Oozeling' pet gives players a slight debuff when summoned.",
	"The 'Lazy Peons' in the Orc starting zone are a callback to a Warcraft III mission.",
	"The 'Underbelly' in Dalaran is a hot spot for PvP... and for fishing rare items.",
	"The Aldor and Scryer factions in Shattrath used to fight openly in the city.",
	"The Alliance and Horde fight over resources in Silithus, even though it’s a barren wasteland.",
	"The Argent Dawn faction was formed to protect Azeroth from undead threats after the Third War.",
	"The Argent Tournament grounds in Northrend were originally going to be a raid zone.",
	"The Argent Tournament was a test of strength for heroes preparing to face the Lich King.",
	"The Ashbringer sword was rumored for years before it became a real item in Wrath of the Lich King.",
	"The Ashbringer sword was said to be forged from pure Light and could destroy the undead instantly.",
	"The Auction House was originally so buggy that gold duping exploits became rampant.",
	"The Barrens is so vast that players once joked it should have its own chat channel.",
	"The Barrens used to have an NPC named 'Mankrik’s Wife' before she disappeared.",
	"The Black Temple raid was originally Illidan’s fortress and training ground for Demon Hunters.",
	"The Black Temple was once a sanctuary for the Draenei before Illidan took it over.",
	"The Blackrock Orcs were originally allies of the Horde but betrayed them for power.",
	"The Blackrock Spire dungeon is a massive fortress with hidden corridors and Easter eggs.",
	"The Blackrock clan orcs are known for their loyalty to their warlords and mastery of the forge.",
	"The Blingtron 4000 robot distributes gifts, but it’s also been known to start wars between players.",
	"The Blood Elf capital, Silvermoon, still bears scars from Arthas’ attack during the Third War.",
	"The Borean Tundra in Northrend features giant steam vents that keep the zone semi-habitable.",
	"The Brawler’s Guild features increasingly difficult solo challenges for players to conquer.",
	"The Bronze Dragonflight controls the flow of time and protects Azeroth’s history.",
	"The Burning Legion’s leader, Sargeras, was once a champion of the Titans before his fall.",
	"The Burning Legion’s soldiers come from countless conquered worlds across the cosmos.",
	"The Cataclysm expansion flooded the Thousand Needles zone, creating a massive saltwater lake.",
	"The Caverns of Time in Tanaris allow players to witness Azeroth’s most important historical events.",
	"The Crystalsong Forest is named after the powerful crystals growing throughout the zone.",
	"The Dancing Troll Village in Hinterlands is a hidden location with non-stop music.",
	"The Dark Portal is one of the oldest structures in Azeroth, built by the Orcs to invade.",
	"The Dark Portal was originally created by the orc warlock Gul’dan to invade Azeroth.",
	"The Darkmoon Faire features a roller coaster you can actually ride.",
	"The Darkmoon Faire has an eerie forest with glowing eyes that follow you.",
	"The Darkmoon Faire's founder, Silas Darkmoon, is a mysterious gnome who rarely appears in public.",
	"The Darkmoon Faire’s leader, Silas Darkmoon, is rumored to have connections to Old God worship, as evidenced by the Faire’s unsettling atmosphere and cryptic items.",
	"The Darkmoon Rabbit is a hidden world boss inspired by Monty Python.",
	"The Deadmines contains the remains of past adventurers who failed to escape its deadly traps.",
	"The Deadmines dungeon has a hidden parrot named Captain Cookie who can drop loot.",
	"The Death Knight starting experience involves players being forced to slaughter innocent villagers under the Lich King's command.",
	"The Deeprun Tram connects Stormwind and Ironforge but also has a giant underwater tunnel.",
	"The Demon Hunter’s ability to glide comes from their spectral wings.",
	"The Draenei originally fled their homeworld of Argus to escape the Burning Legion.",
	"The Drakkari trolls in Northrend sacrificed their own animal gods to gain power when they were desperate to fight the Scourge.",
	"The Drakkari trolls sacrificed their own gods to protect themselves from the Scourge.",
	"The Emerald Dream is a blueprint of Azeroth, untouched by mortal corruption.",
	"The Emerald Dream is a vision of Azeroth untouched by mortal hands.",
	"The Emerald Dream was originally planned as an expansion but ended up being raid content instead.",
	"The Emerald Nightmare distorts Azeroth’s most serene natural landscapes into horrifying versions, filled with corrupted creatures and twisted flora.",
	"The Emerald Nightmare is a corrupted version of the Emerald Dream, filled with horrors created by the Old God N'Zoth to destroy Azeroth's natural order.",
	"The Emerald Nightmare raid was based on corrupted versions of zones in the Emerald Dream.",
	"The Eternal Palace in Nazjatar is the seat of Queen Azshara’s power.",
	"The Ethereal race is based on sci-fi depictions of energy beings.",
	"The Ethereal race trades in powerful magical artifacts across the cosmos.",
	"The Exodar is a crashed spaceship that the Draenei turned into their capital.",
	"The Fel Reaver in Hellfire Peninsula is infamous for sneaking up on distracted players.",
	"The Fel Reaver in Outland has a surprising amount of fan art, despite traumatizing players.",
	"The Firelands raid features Ragnaros reborn, this time with legs!",
	"The Firelord Ragnaros controls an army of elementals in the Plane of Fire.",
	"The Forsaken Apothecaries conduct experiments in alchemy to create plagues and poisons.",
	"The Forsaken Apothecaries experiment on living humans and animals to refine their deadly plague.",
	"The Forsaken faction was originally neutral but became Horde after Sylvanas joined them.",
	"The Forsaken use blight bombs in battle, a strategy derived from their plague experiments.",
	"The Forsaken were originally part of the Scourge before Sylvanas broke them free.",
	"The Forsaken’s plague experiments often reference real-world toxicology practices.",
	"The Garrison system in Warlords of Draenor lets players build and customize their own base.",
	"The Goblin Zeppelin is powered by Goblin ingenuity—and a lot of duct tape.",
	"The Goldshire innkeeper has one of the most haunted WoW locations upstairs. Don’t visit at night.",
	"The Haunted Memento from Naxxramas summons a shadowy ghost to follow players around.",
	"The Hearthstone card game started as a simple WoW mini-game concept.",
	"The Horde airship captains occasionally argue over the intercom. It's worth eavesdropping on.",
	"The Hozen of Pandaria have their own unique language, often filled with monkey-themed slang.",
	"The Iron Horde in Warlords of Draenor used primitive weapons enhanced by technology.",
	"The Ironforge airport is a hidden area that has existed since Vanilla WoW.",
	"The Jinyu race in Pandaria can 'listen' to the water to predict the future.",
	"The Kalu’ak in Northrend are Tuskarr fishermen who also build intricate carvings.",
	"The Karazhan Chess Event has caused more wipes than actual bosses in that raid.",
	"The Karazhan Crypts, an unused area, contain a section called the 'Upside-Down Sinners,' where bodies float eerily underwater, chained by their feet.",
	"The Leeroy Jenkins meme originated from a player in Upper Blackrock Spire. Never forget.",
	"The Legion invasion events brought infernals crashing down into random zones, causing chaos.",
	"The Lost Isles, the Goblin starting zone, is full of references to pop culture, including Indiana Jones.",
	"The Lost Vikings, a classic Blizzard game, is referenced by NPCs in several WoW locations.",
	"The Lunar Festival holiday event is based on the Chinese New Year.",
	"The Maelstrom is the site of the original Well of Eternity’s destruction.",
	"The Midsummer Fire Festival celebrates Azeroth’s longest days with bonfires and fireworks.",
	"The Moonkin form for Druids is lovingly called 'Boomkin' by the community.",
	"The Murloc language was created by sound designers gargling water into a microphone.",
	"The Naaru are beings of pure light, but they can fall into darkness if corrupted.",
	"The Naga were created when Azshara and her followers were transformed by the Old Gods.",
	"The Netherstorm in Outland is a region torn apart by chaotic arcane energy.",
	"The N’Zoth boss fight in Ny’alotha featured mechanics based on Lovecraftian horror.",
	"The Old Gods whisper to players during certain quests, often sowing doubt and fear.",
	"The Old Gods, like Yogg-Saron and N'Zoth, whisper to players during encounters, with chilling phrases like 'Your heart will explode.'",
	"The Old Gods, such as N'Zoth and Y'Shaarj, thrive on corrupting mortals and driving them insane, often whispering promises of power in exchange for servitude.",
	"The Onyxia Wipe Animation became a viral sensation, based on an actual raid leader’s meltdown.",
	"The Pandaren racial ability ‘Epicurean’ increases the stat boost from food.",
	"The Pandaren racial ability, 'Bouncy,' reduces fall damage by 50%. Pandas are just chill like that.",
	"The Pit of Saron dungeon in Icecrown features Scourge slaves mining saronite, Yogg-Saron’s ‘blood.’",
	"The Pit of Saron dungeon in Icecrown is a frozen mine used by the Scourge.",
	"The Pit of Saron dungeon shows living slaves forced to mine saronite, the blood of Yogg-Saron, until they collapse and die.",
	"The Plaguelands are littered with the remains of entire towns wiped out by the undead plague during the Third War.",
	"The Plaguelands were once a thriving human kingdom before the Scourge wiped it out.",
	"The PvP Arena system was introduced in The Burning Crusade expansion.",
	"The PvP title ‘High Warlord’ was one of the hardest titles to earn in Vanilla WoW.",
	"The Reins of the Grey Riding Camel is one of the most difficult mounts to obtain, requiring rare NPC hunting in Uldum.",
	"The Saronite ore found in Northrend is said to be the blood of Yogg-Saron.",
	"The Scarab Lord title from Ahn'Qiraj is one of the rarest in WoW history.",
	"The Scarlet Crusade believes all non-humans are infected with undeath.",
	"The Scarlet Crusade believes they are purging evil but often target innocent people.",
	"The Scarlet Crusade has some of the most morally questionable NPCs in WoW.",
	"The Scarlet Crusade, a faction devoted to eradicating the undead, often tortures and kills innocent people, believing them to be corrupted by undeath.",
	"The Scarlet Halls dungeon is a training ground for the Scarlet Crusade’s new recruits.",
	"The Scarlet Monastery’s leaders were fanatics who thought undeath could be cured.",
	"The Scepter of the Shifting Sands questline is one of the longest and most epic in WoW history.",
	"The Scourge necropolises were massive death factories, designed to harvest and reanimate the fallen en masse.",
	"The Scourge's necropolises were designed to harvest and reanimate the dead on an industrial scale, turning entire populations into undead armies.",
	"The Sha of Pandaria represent negative emotions like anger, fear, and doubt.",
	"The Sholazar Basin in Northrend was inspired by the Un’Goro Crater in Kalimdor.",
	"The Siege of Orgrimmar raid marked the end of Garrosh Hellscream’s reign as Warchief.",
	"The Silithid race in WoW is inspired by the insect-like Zerg from StarCraft.",
	"The Stormwind park district was destroyed in Cataclysm and only rebuilt years later.",
	"The TCG loot card 'Spectral Tiger' is still one of the most sought-after mounts in WoW.",
	"The Tauren capital, Thunder Bluff, is built on giant mesas for protection against enemies.",
	"The Timbermaw Hold faction in Felwood has some of the hardest-to-please furbolgs in the game.",
	"The Timbermaw Hold tunnels connect Felwood, Winterspring, and Moonglade.",
	"The Timeless Isle features unique items that transform players into frogs, birds, or other animals.",
	"The Timeless Isle in Pandaria has a mysterious shrine where you can ask for fortunes.",
	"The Timeless Isle in Pandaria is filled with Easter eggs, including a giant rubber ducky.",
	"The Timeless Isle is filled with random events, including a mysterious ghost ship.",
	"The Tiny Green Ragdoll toy is one of the creepiest items you can place in your Garrison.",
	"The Turtle Mount is a rare fishing drop and was one of the first mounts added via fishing.",
	"The Tuskarr fishing villages in Northrend have some of the coziest vibes in the game.",
	"The Undercity was built within the ruins of Lordaeron's capital, where the Forsaken rule amid the remnants of Arthas' betrayal and genocide.",
	"The Un’Goro Crater in Kalimdor is inspired by real-life prehistoric locations like the Galápagos Islands.",
	"The Void Elves were exiled Blood Elves who embraced the void for power.",
	"The Void whispers to anyone who taps into its power, driving weaker minds to madness with promises of infinite knowledge.",
	"The Vrykul of Northrend believe only the strongest warriors deserve to ascend to Valhalla.",
	"The Vrykul were originally intended to be a playable race in Wrath of the Lich King.",
	"The Wailing Caverns dungeon emits faint, ghostly wails, allegedly the spirits of those trapped in the caverns.",
	"The Wailing Caverns was originally going to be a solo dungeon.",
	"The Wailing Caverns, a low-level dungeon, hides the twisted experiments of Druids of the Fang, who sought to corrupt nature itself.",
	"The Wand of Animation lets you bring objects to life. Some players use it for mischief.",
	"The Wandering Isle, the Pandaren starting zone, is carried on the back of a giant turtle.",
	"The Wandering Isle’s name refers to the fact that it floats and travels across the ocean.",
	"The War of the Ancients began when Queen Azshara and her Highborne attempted to summon Sargeras to Azeroth, leading to untold death and destruction.",
	"The Whispering Forest event includes eerie faerie dragons performing rituals in the dead of night, with no explanation given in the game.",
	"The Whispering Forest in Tirisfal Glades has a secret event where faerie dragons perform a ritual.",
	"The Whispering Forest in Tirisfal Glades is home to a ritual where faerie dragons gather to perform a haunting, otherworldly ceremony.",
	"The Wind Rider mounts used by the Horde are inspired by lions with bat wings.",
	"The Worgen curse originated from a druidic ritual gone wrong.",
	"The Wrathgate betrayal saw the Forsaken unleash a plague that melted Horde and Alliance forces alive, leaving piles of steaming corpses.",
	"The Wrathgate cinematic depicts one of the darkest betrayals in WoW history, where Putress and the Forsaken unleash a plague, killing Alliance, Horde, and Scourge forces indiscriminately.",
	"The Wrathion NPC in Mists of Pandaria is one of the last uncorrupted Black Dragons.",
	"The Zandalari Trolls' Loa gods are based on real-world voodoo and spiritual traditions.",
	"The Zandalari Trolls’ Dazar'alor temple is one of the tallest structures in WoW.",
	"The Zandalari Trolls’ empire predates the Sundering and the splitting of Azeroth into continents.",
	"The Zhevra Plains in the Barrens are home to herds of unique striped creatures.",
	"The Zhevras in the Barrens are based on zebras but have unique horns.",
	"The city of Dalaran has moved three times in WoW’s history.",
	"The city of Suramar in Legion is based on the height of Nightborne civilization.",
	"The cursed blade Frostmourne consumed the souls of those it killed and enslaved its wielder to the Lich King’s will.",
	"The cursed blade Frostmourne consumed the souls of those it killed, enslaving their spirits for eternity.",
	"The cursed pirate fleet of Helya in Stormheim is composed of souls she captured and bound to her service, denying them peace in the afterlife.",
	"The dance for male Trolls is based on Michael Jackson's 'Thriller.'",
	"The dungeon Scholomance is named after a legendary school of black magic from folklore.",
	"The dungeon Scholomance was once a secret academy for necromancers under Kel’Thuzad’s command.",
	"The first level 60 player in Vanilla WoW took about 10 days of /played time.",
	"The first player to hit max level in WoW Classic did it by grinding mobs for days straight.",
	"The first raid boss in WoW, Onyxia, has over 50 voice lines to taunt players.",
	"The first world-first raid boss kill was Ragnaros in Molten Core.",
	"The game still references Kael'thas Sunstrider's infamous line, 'Tempest Keep was merely a setback!'",
	"The game’s original developers hid jokes in item tooltips, like 'This sword doesn’t actually exist.'",
	"The game’s original developers used to run events on live servers disguised as NPCs.",
	"The giant trees in Ashenvale are thousands of years old and protected by the Night Elves.",
	"The goblins' obsession with explosives has caused more than one in-game accident.",
	"The haunted Karazhan crypts, a location originally cut from the game, contain chilling areas like the 'Upside-Down Sinners,' where corpses float eerily underwater.",
	"The haunted inn in Goldshire (on some servers) has a second floor where children appear at night in a pentagram formation.",
	"The haunted manor in Drustvar is filled with ghostly whispers and objects that move on their own, hinting at the Heartsbane Coven's dark magic.",
	"The infamous 'Barrens Chat' was where most Chuck Norris jokes were born in WoW.",
	"The infamous Corrupted Blood incident became a case study for epidemiologists.",
	"The legendary Thunderfury sword was often memed in trade chat as 'Thunderfury, Blessed Blade of the Windseeker.'",
	"The legendary cloak questline in Mists of Pandaria made players hate running LFR repeatedly.",
	"The legendary weapon Sulfuras was inspired by Norse mythology’s hammer of the gods.",
	"The loading screen tips have a 0.01% chance to display 'You are not prepared!' as a joke.",
	"The model for Gnomish Engineers’ devices was inspired by old steampunk aesthetics.",
	"The most expensive mount in WoW history is the Mighty Caravan Brutosaur, aka the 'Longboi.'",
	"The most infamous quest in Vanilla was 'Deep Ocean, Vast Sea'—because no one had water breathing.",
	"The mount ‘Big Love Rocket’ is one of the rarest in-game items, only available during Love is in the Air.",
	"The mount ‘Headless Horseman’s Steed’ only drops during the Hallow’s End event.",
	"The mount ‘Invincible’ is named after Arthas’ loyal steed, who died before his transformation into the Lich King.",
	"The mount ‘Reins of the Traveler’s Tundra Mammoth’ includes vendors that sell and repair items.",
	"The mount ‘Sky Golem’ allows players to harvest herbs without dismounting.",
	"The music in Grizzly Hills is so beloved that it’s often played outside the game.",
	"The music in Storm Peaks is inspired by Nordic mythology and landscapes.",
	"The neutral Pandaren starting zone is technically a giant turtle named Shen-zin Su.",
	"The original AQ War Effort event required entire servers to work together to unlock the raid.",
	"The original Dark Portal event caused crashes when too many players showed up.",
	"The original Naxxramas raid had bosses so hard that most guilds never finished it.",
	"The original WoW Alpha featured a zone called 'Dragon Isles' that wasn’t released until Dragonflight.",
	"The original WoW Alpha included fully functional flying mounts, but they were removed for Vanilla.",
	"The original design for Death Knights in Vanilla WoW was an alternate hero class that started at level 1.",
	"The pandas in Valley of the Four Winds sometimes wave at you if you emote back.",
	"The pet Pepe has costumes for different in-game holidays, including a pirate hat!",
	"The questline to obtain the legendary weapon Atiesh required raiding and months of dedication.",
	"The rare spawn ‘Loque’nahak’ is a Spirit Beast highly sought after by hunters.",
	"The sword 'Ashbringer' was teased for years before finally being added in Wrath of the Lich King.",
	"The term 'Leeroy Jenkins' is now officially in the Merriam-Webster dictionary as a meme.",
	"The term 'Void' in WoW refers to a dark, shadowy power that opposes the Light.",
	"The title 'Salty' can be earned by completing the most difficult fishing achievements in WoW.",
	"The town of Goldshire is infamous on certain RP servers for… unconventional activities.",
	"The toy 'Piccolo of the Flaming Fire' makes everyone nearby dance. Perfect for raid trolling.",
	"The toy 'Wand of Simulated Life' lets players bring inanimate objects to life temporarily.",
	"The toy ‘Ethereal Soul-Trader’ lets players summon a vendor from another dimension.",
	"The toy ‘Fishing Chair’ allows players to sit while fishing, adding flavor to the profession.",
	"The toy ‘Gnomish X-Ray Specs’ lets players see everyone as skeletons.",
	"The toy ‘Piccolo of the Flaming Fire’ forces everyone nearby to dance.",
	"The toy ‘Robo-Gnomebulator’ temporarily turns players into gnomish robots.",
	"The toy ‘Sack of Starfish’ summons flying starfish to follow players around.",
	"The toy ‘Super Simian Sphere’ transforms players into a glowing ape inside a magical bubble.",
	"The troll city of Zul’Gurub was once a raid but is now a 5-player dungeon.",
	"The underwater ruins in Vashj'ir are inhabited by naga and feature skeletal remains of creatures never identified by lore.",
	"The underwater ruins in Vashj’ir were once part of a thriving Kaldorei empire.",
	"The underwater ruins of Vashj'ir are remnants of an ancient Naga empire.",
	"The underwater zone Nazjatar was ruled by Queen Azshara for millennia.",
	"The underwater zone Vashj’ir was Blizzard’s first fully aquatic environment.",
	"The zone Winterspring is known for its pristine snow and rare Frostsaber mounts.",
	"There's a gnome NPC in Northrend who complains about how cold it is—he's not wrong.",
	"There's a legendary trinket called 'The Skull of Gul'dan,' but Gul'dan isn't amused.",
	"There's a rare mount in Nazjatar that drops from a crab called 'Snapdragon.'",
	"There's a secret fishing spot in Booty Bay that increases your chance for rare catches.",
	"There's a secret pet in the game called 'Mr. Bigglesworth' that references Naxxramas' boss Kel'Thuzad.",
	"There's a secret underwater cave in Zangarmarsh with glowing mushrooms.",
	"There's a turtle NPC named Lvl ?? Elite who is a parody of TMNT in Pandaria.",
	"There’s a giant skeleton in the Shimmering Flats that might belong to a forgotten titan.",
	"There’s a gnome NPC in Gnomeregan who complains about the radiation being 'totally safe.'",
	"There’s a gnome NPC in the Brawler’s Guild who references the Rocky movies.",
	"There’s a graveyard in Duskwood with headstones that tell jokes if you read them.",
	"There’s a hidden NPC named Captain Placeholder that used to stand in for unfinished content.",
	"There’s a hidden cave in Azshara where developers left untextured walls as an inside joke.",
	"There’s a hidden cave in the Badlands filled with skeletons and treasure maps.",
	"There’s a hidden panda NPC in Pandaria who offers wise advice and riddles.",
	"There’s a hidden tribute to Robin Williams in Draenor: a genie NPC called 'Robin.'",
	"There’s a hidden tribute to StarCraft in Azshara, with zergling-like creatures near the shoreline.",
	"There’s a hidden underwater cave in Vashj’ir filled with glowing jellyfish.",
	"There’s a miniature version of Stormwind Keep hidden in the Deeprun Tram tunnel.",
	"There’s a rare fish in Stranglethorn Vale called the Dezian Queenfish that’s purely decorative.",
	"There’s a rare gnome in Borean Tundra who rides a mechanical spider mount.",
	"There’s a rare mob called 'The Rake' that became famous for being the best Hunter pet in Classic WoW.",
	"There’s a rare mob in the Jade Forest that has a pet panda named after a Blizzard employee.",
	"There’s a rare spawn in Tanaris called Caliph Scorpidsting. He drops a scorpion that isn’t even a pet.",
	"There’s a rare spawn named 'Time-Lost Proto-Drake' that hunters have searched for years to tame.",
	"There’s a rare vanity pet called 'Bananas' that’s a baby monkey wearing a diaper.",
	"There’s a secret bar hidden in Booty Bay where NPCs argue over pirate treasure.",
	"There’s a secret chicken farm in Hillsbrad Foothills where chickens wander free.",
	"There’s a secret hatch in Uldum referencing the TV show Lost.",
	"There’s a secret location in Icecrown where a ghostly mage trains forever in solitude.",
	"There’s a secret tribute to a Blizzard employee in the Storm Peaks, featuring their favorite pet.",
	"There’s a toy called the 'Disco Ball' that turns every nearby player into a dancer.",
	"There’s a waterfall in Pandaria that has a hidden cave with an abandoned tea set.",
	"Vanilla WoW had no in-game map markers. You just had to remember where stuff was.",
	"Vanilla WoW had no transmog system, and players had to deal with mismatched armor sets.",
	"Vanilla WoW required players to spend gold to learn new abilities, which became expensive at higher levels.",
	"Warlocks in Vanilla were so OP that guilds demanded you level one for raids.",
	"Worgen used to be a part of the Scythe of Elune storyline before they became playable.",
	"Yogg-Saron claims responsibility for Deathwing's madness, whispering, 'He was merely a puppet. All were puppets.'",
	"Yogg-Saron, the Old God imprisoned in Ulduar, whispers maddening secrets to players, claiming to have influenced Deathwing and other major events in Azeroth's history.",
	"You can find NPCs in Azeroth arguing about which came first, the murloc or the egg.",
	"You can find NPCs in Dalaran who look suspiciously like Harry Potter characters.",
	"You can find a broken statue of Arthas hidden in Icecrown, symbolizing his tragic fall.",
	"You can find a penguin pet in Northrend that waddles around without a care in the world.",
	"You can find a rare chicken in Elwynn Forest that starts a hidden quest if you /chicken at it.",
	"You can find a small shrine to Uther the Lightbringer in the Plaguelands.",
	"You can find a small tribute to StarCraft inside the Engineering profession.",
	"You can find an NPC named 'Haris Pilton' selling overpriced bags as a parody of Paris Hilton.",
	"You can find penguins in Northrend who will slide down icy slopes if you wait long enough.",
	"You can find the remains of a crashed goblin airship in Azshara.",
	"You can sometimes hear NPCs gossiping about players in inns if you stand close enough.",
	"You can still find remains of Old God minions buried deep within Silithus.",
}
